#### Importing Libraries

In [9]:
import pandas as pd
from IPython.display import display
import numpy as np
import os

#### Loading and Viewing CSV from input folder

In [10]:
df = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/input/Compass_Data_1.csv")
display(df.sample(15))

,Alarm DateTime,Dispatch Total Response Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Total On Scene Time,Total Time Alarm to Last Unit Cleared
26879,2026-03-26 19:22:19.000,359.0,0,2609505,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.012455,-78.940819,B Shift,FS 2,1,441.0,795
8660,2025-12-19 13:33:14.000,387.0,0,2540534,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.024586,-78.909454,B Shift,CAD Beat 07,1,1746.0,2129
26575,2026-03-17 14:23:15.000,357.0,0,2608441,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.013042,-78.939270,B Shift,FS 2,1,401.0,743
19567,2025-09-23 18:17:53.000,628.0,0,2530500,"Smoke detector activation, no fire - unintenti...",700 - False Alarm,35.972012,-78.900055,C Shift,CAD Beat 04,3,1075.0,1563
27352,2026-01-21 19:35:27.000,396.0,0,2602421,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.906143,-78.906776,C Shift,FS 18,1,896.0,1288
2638,2026-04-21 19:42:29.000,357.0,0,2612435,"False alarm or false call, other",700 - False Alarm,35.879505,-78.855766,C Shift,FS 19,2,1066.0,1329
10496,2025-08-05 07:23:57.000,410.0,0,2524763,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.013058,-78.939125,C Shift,CAD Beat 02,1,1284.0,1672
11261,2025-09-10 01:33:33.000,291.0,0,2528958,Building fire,100 - Fire,35.973011,-78.891525,A Shift,CAD Beat 04,19,12931.0,13091
11078,2025-08-16 20:05:59.000,261.0,0,2526077,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.926846,-78.832222,A Shift,CAD Beat 13,1,1228.0,1481
14105,2026-04-18 14:09:47.000,289.0,0,2612032,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.964375,-78.896919,B Shift,FS 4,2,692.0,964
22123,2025-07-08 12:16:56.000,366.0,0,2521514,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,0.000000,0.000000,C Shift,CAD Beat 02,1,612.0,978
12412,2025-08-27 08:32:23.000,356.0,0,2527338,"False alarm or false call, other",700 - False Alarm,36.044533,-78.891457,A Shift,CAD Beat 07,2,1393.0,1674
28140,2025-09-07 17:58:45.000,219.0,0,2528692,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.904194,-78.941780,A Shift,CAD Beat 18,1,680.0,894
15884,2026-04-15 18:46:09.000,217.0,0,2611714,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.040829,-78.889084,C Shift,FS 7,3,926.0,1129
33598,2025-09-16 09:55:54.000,238.0,0,2529652,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.007408,-78.886787,B Shift,CAD Beat 09,2,562.0,772

In [11]:
print(df.columns.tolist())

['Alarm DateTime', 'Dispatch Total Response Time', 'EMS Apparatus Count', 'Incident Number', 'Incident Type', 'Incident Type Group', 'Latitude', 'Longitude', 'Shift', 'Station', 'Suppression Apparatus Count', 'Total On Scene Time', 'Total Time Alarm to Last Unit Cleared']

#### Splitting Alarm Date Time to Alarm Date & Alarm Time

In [12]:
# Ensuring datetime type
df["Alarm DateTime"] = pd.to_datetime(df["Alarm DateTime"])

# Splitting into separate columns
df["Alarm Date"] = df["Alarm DateTime"].dt.date.astype(str)   # YYYY-MM-DD
df["Alarm Time"] = df["Alarm DateTime"].dt.time.astype(str)   # HH:MM:SS

# Dropping original column
df = df.drop(columns=["Alarm DateTime"])

# Moving new columns to the front
cols = ["Alarm Date", "Alarm Time"] + [c for c in df.columns if c not in ["Alarm Date", "Alarm Time"]]
df = df[cols]

display(df.sample(5))

,Alarm Date,Alarm Time,Dispatch Total Response Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Total On Scene Time,Total Time Alarm to Last Unit Cleared
8844,2025-09-20,09:49:05,203.0,0,2530105,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.977493,-78.934357,B Shift,CAD Beat 05,1,982.0,1169
18468,2026-02-04,17:50:14,143.0,0,2603910,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.883812,-78.846565,A Shift,FS 19,1,1302.0,1433
13760,2025-05-10,08:15:36,352.0,0,2514698,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,0.000000,0.000000,A Shift,CAD Beat 18,1,838.0,1190
4203,2026-04-05,22:00:16,384.0,0,2610597,Smoke detector activation due to malfunction,700 - False Alarm,35.908257,-78.987968,A Shift,FS 16,1,932.0,1232
15164,2025-07-23,09:56:20,636.0,0,2523220,"Medical assist, assist EMS crew",300 - Rescue & EMS,0.000000,0.000000,C Shift,CAD Beat 02,1,554.0,1190

#### Coverting Time to Decimal Minutes

In [13]:
df["Dispatch Total Response Time (min)"] = df["Dispatch Total Response Time"] / 60
df["Total On Scene Time (min)"] = df["Total On Scene Time"] / 60
df["Total Time Alarm to Last Unit Cleared (min)"] = df["Total Time Alarm to Last Unit Cleared"] / 60

# Dropping original columns
df = df.drop(columns=["Dispatch Total Response Time"])
df = df.drop(columns=["Total On Scene Time"])
df = df.drop(columns=["Total Time Alarm to Last Unit Cleared"])
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
1964,2025-08-13,22:56:24,0,2525742,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.058220,-78.887772,B Shift,CAD Beat 07,1,6.600000,4.216667,10.683333
5406,2025-09-19,08:07:09,0,2529966,Citizen complaint,900 - Special Incident,35.991615,-78.871292,C Shift,CAD Beat 03,1,5.383333,2.550000,5.783333
21633,2025-11-03,16:40:20,0,2535299,No incident found on arrival at dispatch address,600 - Good Intent Call,35.881989,-78.867172,C Shift,CAD Beat 19,1,10.483333,5.583333,15.833333
29116,2026-04-08,00:47:19,0,2610844,"Outside rubbish, trash or waste fire",100 - Fire,35.964191,-78.907623,A Shift,FS 4,1,5.950000,4.483333,10.266667
30887,2026-03-28,11:26:22,0,2609674,"Municipal alarm system, malicious false alarm",700 - False Alarm,35.925732,-78.914841,B Shift,FS 12,2,6.450000,12.266667,18.516667

#### Dropping "Shift" from the Shift column

In [14]:
df["Shift"] = df["Shift"].str.strip().str.replace("Shift", "", regex=False)
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
1958,2026-02-09,09:08:03,0,2604411,Motor vehicle accident with no injuries.,300 - Rescue & EMS,35.917847,-78.862244,B,FS 13,3,8.766667,17.033333,24.500000
29951,2026-03-05,02:23:42,0,2607039,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.997345,-78.917252,B,FS 5,1,6.483333,5.000000,11.300000
15452,2025-11-24,09:59:04,0,2537759,"Detector activation, no fire - unintentional",700 - False Alarm,36.018085,-78.902550,C,CAD Beat 02,2,5.983333,10.950000,16.166667
3365,2025-12-05,13:50:57,0,2538967,Dispatched & canceled en route,600 - Good Intent Call,36.027317,-78.916435,C,CAD Beat 02,1,NaN,NaN,2.033333
1230,2025-10-03,18:32:53,0,2531633,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.879433,-78.845779,B,CAD Beat 19,1,4.200000,10.016667,13.916667

#### Dropping "FS" and "CAD Beat" from Station Column and any zero in front of the number e.g in 05

In [15]:
df["Station"] = (
    df["Station"]
    .str.strip()
    .str.replace("FS", "", regex=False)
    .str.replace("CAD Beat", "", regex=False)
    .str.replace(r"\b0+(\d+)\b", r"\1", regex=True)
)

display(df.sample(50))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
19421,2025-10-19,10:04:39,0,2533504,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.951431,-78.905624,C,4,1,5.500000,21.683333,26.583333
11708,2025-05-12,14:45:23,0,2514929,Smoke or odor removal,500 - Service Call,0.000000,0.000000,A,1,5,9.416667,8.483333,17.900000
30709,2026-03-13,10:18:16,0,2608021,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.095390,-78.917664,B,14,1,7.400000,12.783333,19.783333
4439,2025-09-25,08:38:28,0,2530666,Gas leak (natural gas or LPG),400 - Hazardous Condition,36.067505,-78.948944,C,10,5,10.283333,32.883333,41.233333
10795,2025-07-03,09:50:01,0,2520877,"Unintentional transmission of alarm, other",700 - False Alarm,0.000000,0.000000,B,19,2,9.400000,3.066667,12.466667
7896,2025-05-04,14:01:53,0,2514035,"Medical assist, assist EMS crew",300 - Rescue & EMS,0.000000,0.000000,B,16,1,7.516667,13.400000,20.916667
11687,2025-07-31,06:36:57,0,2524194,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.987568,-78.887474,A,3,1,5.100000,11.566667,16.466667
7210,2025-06-27,01:55:12,0,2520118,Sprinkler activation due to malfunction,700 - False Alarm,0.000000,0.000000,A,12,2,11.700000,7.566667,19.266667
21307,2026-04-25,14:33:49,0,2612832,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.004986,-78.888634,B,1,1,5.100000,7.250000,12.200000
6121,2025-12-05,08:19:15,0,2538933,"Excessive heat, scorch burns with no ignition","200 - Overpressure Rupture, Explosion, Overheat",36.064507,-78.904785,C,7,5,5.116667,19.083333,22.883333
13270,2025-07-01,15:01:53,0,2520682,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,0.000000,0.000000,B,10,2,7.766667,37.183333,44.950000
26378,2025-10-08,09:08:12,0,2532150,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.042641,-78.893700,C,7,2,3.400000,33.416667,36.316667
26202,2026-04-14,06:58:11,0,2611538,No incident found on arrival at dispatch address,600 - Good Intent Call,36.010086,-78.899750,A,1,4,4.816667,5.100000,8.816667
21559,2025-11-29,08:34:11,0,2538273,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.046654,-78.980972,A,10,1,4.866667,24.783333,29.283333
28962,2025-05-16,00:32:51,0,2515360,Smoke detector activation due to malfunction,700 - False Alarm,0.000000,0.000000,B,5,2,6.850000,6.766667,13.616667
11040,2026-03-26,13:42:23,0,2609464,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.046745,-78.937401,B,10,1,8.283333,6.483333,13.816667
18447,2026-04-18,10:23:19,0,2612006,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.064507,-78.904785,B,7,1,8.383333,30.266667,38.350000
11925,2025-06-13,14:19:19,0,2518507,Smoke detector activation due to malfunction,700 - False Alarm,0.000000,0.000000,A,18,2,4.683333,7.800000,12.483333
11508,2025-06-10,13:08:24,0,2518183,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,0.000000,0.000000,C,LEB2,1,5.700000,9.916667,15.616667
7124,2026-03-20,21:54:45,0,2608839,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.042667,-78.918457,C,7,1,5.616667,6.250000,11.666667
4915,2025-08-29,19:22:37,0,2527655,"Outside rubbish, trash or waste fire",100 - Fire,36.045654,-78.838890,A,RED1,1,6.666667,6.700000,11.950000
11329,2025-08-05,09:28:59,0,2524777,No incident found on arrival at dispatch address,600 - Good Intent Call,36.032799,-78.964897,C,10,2,14.133333,0.000000,12.066667
27030,2025-10-15,11:06:26,0,2532968,Motor vehicle accident with no injuries.,300 - Rescue & EMS,35.986423,-78.895477,A,1,5,8.066667,5.266667,8.333333
31847,2026-02-24,16:21:46,0,2606174,"Steam, other gas mistaken for smoke, other",600 - Good Intent Call,36.046665,-78.901924,B,7,1,3.116667,8.466667,10.250000
22994,2025-12-16,01:42:05,0,2540108,"Smoke detector activation, no fire - unintenti...",700 - False Alarm,36.064507,-78.904785,B,7,4,5.000000,13.883333,18.016667
28965,2025-05-14,12:56:34,0,2515181,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,0.000000,0.000000,A,16,1,8.966667,13.500000,22.466667
29159,2025-12-06,20:44:06,0,2539113,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.906445,-78.935768,A,18,1,4.350000,1.466667,5.733333
13760,2025-05-10,08:15:36,0,2514698,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,0.000000,0.000000,A,18,1,5.866667,13.966667,19.833333
32268,2025-07-19,22:22:05,0,2522843,"False alarm or false call, other",700 - False Alarm,0.000000,0.000000,C,RAL,3,10.350000,3.150000,13.500000
9784,2025-11-11,08:39:59,0,2536211,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.022488,-78.953522,B,10,3,3.200000,11.900000,14.500000
13130,2025-12-08,20:00:26,0,2539315,"Alarm system activation, no fire - unintentional",700 - False Alarm,36.098938,-78.860191,A,15,2,3.083333,11.466667,13.033333
703,2025-07-06,12:47:33,0,2521239,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,0.000000,0.000000,C,6,1,3.600000,16.500000,20.100000
3100,2025-07-21,00:13:29,0,2522955,No incident found on arrival at dispatch address,600 - Good Intent Call,0.000000,0.000000,B,5,1,4.933333,10.783333,15.716667
26004,2026-02-10,21:28:57,0,2604610,No incident found on arrival at dispatch address,600 - Good Intent Call,35.991627,-78.886063,A,1,1,4.700000,3.616667,7.666667
2077,2025-11-26,16:28:54,0,2538012,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.942635,-78.988327,B,16,1,7.683333,14.883333,22.333333
5345,2026-02-07,17:28:07,0,2604242,"Public service assistance, other",500 - Service Call,35.890514,-78.960175,C,16,1,14.300000,5.016667,15.166667
7561,2025-06-02,14:44:15,0,2517272,"Medical assist, assist EMS crew",300 - Rescue & EMS,0.000000,0.000000,A,1,1,5.166667,3.133333,8.300000
394,2025-10-12,02:28:52,0,2532600,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.973846,-78.961716,A,11,1,6.383333,13.250000,19.516667
26765,2025-05-26,22:15:16,0,2516488,Alarm system sounded due to malfunction,700 - False Alarm,0.000000,0.000000,C,2,2,5.333333,3.916667,9.250000
27638,2025-07-16,23:07:16,0,2522505,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,0.000000,0.000000,B,14,1,7.733333,2.433333,10.166667
12670,2025-12-18,16:50:23,0,2540416,"Vehicle accident, general cleanup",400 - Hazardous Condition,35.964214,-78.894997,C,4,1,0.066667,2.150000,2.150000
28553,2026-02-26,17:10:50,0,2606405,"Malicious, mischievous false call, other",700 - False Alarm,35.938805,-78.927856,B,6,2,5.983333,4.983333,10.833333
2920,2025-08-25,16:46:04,0,2527162,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.923016,-78.761185,A,DMRA,1,4.783333,3.900000,8.333333
33390,2026-04-17,22:54:22,0,2611968,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.039349,-78.884911,C,9,1,5.783333,4.183333,9.850000
6527,2025-09-20,13:02:49,0,2530121,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.998970,-78.903740,B,1,1,3.700000,5.400000,8.466667
33860,2025-07-24,15:54:16,0,2523403,No incident found on arrival at dispatch address,600 - Good Intent Call,0.000000,0.000000,A,9,1,3.716667,2.683333,6.400000
5616,2025-06-19,21:23:16,0,2519262,Carbon monoxide incident,400 - Hazardous Condition,0.000000,0.000000,C,8,2,23.433333,0.200000,23.633333
21777,2025-05-05,04:25:16,0,2514083,"Medical assist, assist EMS crew",300 - Rescue & EMS,0.000000,0.000000,B,4,1,6.133333,5.233333,11.366667
6551,2025-06-23,00:50:59,0,2519562,Sprinkler activation due to malfunction,700 - False Alarm,0.000000,0.000000,B,10,2,11.150000,73.400000,84.550000
1096,2025-11-25,18:01:46,0,2537896,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.992180,-78.848038,A,3,2,7.250000,14.800000,22.000000

#### Exporting File to Output Folder

In [16]:
# Ensuring output folder exists
os.makedirs("output", exist_ok=True)

# Exporting cleaned dataframe
file_path = "C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/output/Compass_Data_1_Cleaned.csv"
df.to_csv(file_path, index=False)

print("Export successful: Compass_Data_1_Cleaned.csv has been created in the output folder.")

Export successful: Compass_Data_1_Cleaned.csv has been created in the output folder.