#### Importing Libraries

In [58]:
import pandas as pd
from IPython.display import display
import numpy as np
import os

#### Loading and Viewing CSV from input folder

In [59]:
df = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/input/Compass_Data_1.csv")
display(df.sample(15))

,Alarm DateTime,Dispatch Total Response Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Total On Scene Time,Total Time Alarm to Last Unit Cleared,Apparatus Type
32646,2025-08-07 16:49:04.000,260.0,0.0,2525059,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.972870,-78.889221,C Shift,CAD Beat 04,1.0,320.0,564.0,"Medical & rescue unit, other"
33111,2025-09-10 13:03:05.000,369.0,0.0,2529011,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.958126,-78.966362,C Shift,CAD Beat 06,1.0,672.0,1037.0,Engine
49260,2025-06-28 09:31:14.000,299.0,0.0,2520264,"Smoke detector activation, no fire - unintenti...",700 - False Alarm,0.000000,0.000000,A Shift,CAD Beat 09,2.0,83.0,382.0,Engine
53714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Truck or aerial
14626,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chief officer car
39277,2025-06-02 23:11:35.000,NaN,0.0,2517325,Dispatched & canceled en route,600 - Good Intent Call,0.000000,0.000000,A Shift,CAD Beat 18,1.0,NaN,395.0,Engine
971,2025-06-01 18:40:46.000,332.0,0.0,2517181,"Unintentional transmission of alarm, other",700 - False Alarm,0.000000,0.000000,B Shift,CAD Beat 17,1.0,568.0,900.0,Engine
52648,2025-06-16 17:45:30.000,354.0,0.0,2518896,Removal of victim(s) from stalled elevator,300 - Rescue & EMS,0.000000,0.000000,B Shift,CAD Beat 04,2.0,2116.0,2470.0,Engine
14304,2026-02-09 17:39:24.000,209.0,0.0,2604471,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.049099,-78.911362,B Shift,FS 7,1.0,572.0,724.0,Engine
4285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other apparatus/resource
62477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Truck or aerial
9387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Quint
22700,2025-09-26 21:47:06.000,620.0,0.0,2530860,Dispatched & canceled en route,600 - Good Intent Call,36.003021,-78.869759,A Shift,CAD Beat 09,1.0,5.0,612.0,Engine
36771,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Truck or aerial
28254,2026-04-04 18:39:39.000,277.0,0.0,2610467,Rescue or EMS standby,300 - Rescue & EMS,35.922386,-78.918915,C Shift,FS 12,1.0,273.0,545.0,"Medical & rescue unit, other"

In [60]:
print(df.columns.tolist())

['Alarm DateTime', 'Dispatch Total Response Time', 'EMS Apparatus Count', 'Incident Number', 'Incident Type', 'Incident Type Group', 'Latitude', 'Longitude', 'Shift', 'Station', 'Suppression Apparatus Count', 'Total On Scene Time', 'Total Time Alarm to Last Unit Cleared', 'Apparatus Type']

#### Splitting Alarm Date Time to Alarm Date & Alarm Time

In [61]:
# Ensuring datetime type
df["Alarm DateTime"] = pd.to_datetime(df["Alarm DateTime"])

# Splitting into separate columns
df["Alarm Date"] = df["Alarm DateTime"].dt.date.astype(str)   # YYYY-MM-DD
df["Alarm Time"] = df["Alarm DateTime"].dt.time.astype(str)   # HH:MM:SS

# Dropping original column
df = df.drop(columns=["Alarm DateTime"])

# Moving new columns to the front
cols = ["Alarm Date", "Alarm Time"] + [c for c in df.columns if c not in ["Alarm Date", "Alarm Time"]]
df = df[cols]

display(df.sample(5))

,Alarm Date,Alarm Time,Dispatch Total Response Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Total On Scene Time,Total Time Alarm to Last Unit Cleared,Apparatus Type
30677,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine
58548,2026-02-22,02:24:24,250.0,0.0,2605902,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.936375,-78.785156,A Shift,FS 17,1.0,578.0,806.0,Engine
36096,2025-10-11,00:41:12,327.0,0.0,2532480,"Excessive heat, scorch burns with no ignition","200 - Overpressure Rupture, Explosion, Overheat",35.990757,-78.908333,C Shift,CAD Beat 05,12.0,566.0,737.0,Truck or aerial
35183,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chief officer car
52580,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Truck or aerial

#### Coverting Time to Decimal Minutes

In [62]:
df["Dispatch Total Response Time (min)"] = df["Dispatch Total Response Time"] / 60
df["Total On Scene Time (min)"] = df["Total On Scene Time"] / 60
df["Total Time Alarm to Last Unit Cleared (min)"] = df["Total Time Alarm to Last Unit Cleared"] / 60

# Dropping original columns
df = df.drop(columns=["Dispatch Total Response Time"])
df = df.drop(columns=["Total On Scene Time"])
df = df.drop(columns=["Total Time Alarm to Last Unit Cleared"])
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
22066,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine,NaN,NaN,NaN
34798,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Truck or aerial,NaN,NaN,NaN
49083,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine,NaN,NaN,NaN
20050,2025-09-20,22:51:51,0.0,2530177,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.998943,-78.835800,B Shift,CAD Beat 08,1.0,Engine,9.650000,13.083333,22.083333
27445,2026-04-13,06:17:12,0.0,2611412,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.993324,-78.880165,B Shift,FS 3,1.0,Engine,6.216667,1.666667,7.600000

#### Dropping "Shift" from the Shift column

In [63]:
df["Shift"] = df["Shift"].str.strip().str.replace("Shift", "", regex=False)
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
60267,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Truck or aerial,NaN,NaN,NaN
33541,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Medical & rescue unit, other",NaN,NaN,NaN
48172,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Quint,NaN,NaN,NaN
6696,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Truck or aerial,NaN,NaN,NaN
23004,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Truck or aerial,NaN,NaN,NaN

#### Dropping "FS" and "CAD Beat" from Station Column and any zero in front of the number e.g in 05

In [64]:
df["Station"] = (
    df["Station"]
    .astype(str)
    .str.strip()
    .str.replace("FS", "", regex=False)
    .str.replace("CAD Beat", "", regex=False)
    .str.replace(r"[^\d]", "", regex=True)   # keeping only digits
)

# Converting to numeric and force integer
df["Station"] = pd.to_numeric(df["Station"], errors="coerce")
df = df.dropna(subset=["Station"])
df["Station"] = df["Station"].astype(int)

display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
6999,2026-02-24,06:33:33,0.0,2606120,Dispatched & canceled en route,600 - Good Intent Call,35.987568,-78.887474,A,3,1.0,"Medical & rescue unit, other",3.916667,0.250000,3.983333
49971,2025-09-10,01:31:12,0.0,2528957,"Alarm system activation, no fire - unintentional",700 - False Alarm,35.901867,-78.867699,A,13,4.0,Chief officer car,15.550000,9.333333,23.800000
52594,2025-07-22,09:08:46,0.0,2523094,Dispatched & canceled en route,600 - Good Intent Call,0.000000,0.000000,B,18,1.0,Engine,NaN,NaN,9.700000
14982,2025-11-12,09:56:30,0.0,2536331,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.974327,-78.840706,A,3,1.0,Truck or aerial,8.550000,38.166667,46.550000
33488,2026-04-21,16:51:26,0.0,2612417,Police matter,500 - Service Call,36.075745,-78.909599,C,7,2.0,Engine,4.933333,14.233333,18.966667

#### Filtering out Stations that not Stations 1-19

In [65]:
# Converting Station to numeric (invalid values become NaN)
df["Station"] = pd.to_numeric(df["Station"], errors="coerce")

# Keeping only stations 1–19
df = df[df["Station"].between(1, 19)]

display(df.sample(5))

print("June rows:", pd.to_datetime(df["Alarm Date"], errors="coerce").dt.month.eq(6).sum())

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
6158,2026-05-29,13:31:12,0.0,2616627,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.011459,-78.936562,B,2,1.0,Engine,6.633333,17.600000,22.166667
53165,2026-04-01,11:28:10,0.0,2610088,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.982388,-78.829773,B,8,1.0,Quint,4.616667,20.783333,24.633333
6628,2026-05-07,04:04:33,0.0,2614130,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.000378,-78.864731,C,3,1.0,Engine,5.200000,29.533333,34.600000
16337,2025-12-16,09:11:00,0.0,2540129,"Detector activation, no fire - unintentional",700 - False Alarm,35.973400,-78.895889,C,4,3.0,Engine,7.166667,1.066667,6.966667
46063,2025-07-15,23:41:01,0.0,2522383,Water or steam leak,500 - Service Call,0.000000,0.000000,A,16,1.0,Engine,10.533333,5.500000,16.033333

June rows: 2994

#### Adding Battalion Column

In [66]:
# Battalion mapping
battalion_map = {
    "1": 1,
    "2": 1,
    "3": 4,
    "4": 1,
    "5": 1,
    "6": 3,
    "7": 2,
    "8": 4,
    "9": 4,
    "10": 2,
    "11": 1,
    "12": 3,
    "13": 4,
    "14": 2,
    "15": 2,
    "16": 3,
    "17": 4,
    "18": 3,
    "19": 3
}

# Adding Battalion column
df["Battalion"] = df["Station"].astype(str).map(battalion_map)

display(df.sample(5))

print("June rows:", pd.to_datetime(df["Alarm Date"], errors="coerce").dt.month.eq(6).sum())

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min),Battalion
28809,2025-09-06,10:19:29,0.0,2528532,Dispatched & canceled en route,600 - Good Intent Call,36.037460,-78.906395,C,7,2.0,Quint,NaN,NaN,4.333333,2
25615,2026-01-22,11:33:23,0.0,2602489,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.052315,-78.975296,A,10,1.0,Engine,8.133333,13.916667,21.333333,2
37162,2025-09-14,01:36:13,0.0,2529390,No incident found on arrival at dispatch address,600 - Good Intent Call,36.009403,-78.899902,A,1,6.0,Other apparatus/resource,7.100000,6.783333,11.233333,1
50333,2025-12-17,23:07:01,0.0,2540345,Dispatched & canceled en route,600 - Good Intent Call,36.004902,-78.952270,B,11,1.0,Engine,NaN,NaN,6.233333,1
3099,2026-05-26,06:24:04,0.0,2616241,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.008484,-78.806915,B,8,1.0,Quint,10.583333,6.800000,17.000000,4

June rows: 2994

#### Exporting File to Output Folder

In [67]:
# Ensuring output folder exists
os.makedirs("output", exist_ok=True)

# Exporting cleaned dataframe
file_path = "C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/output/Compass_Data_1_Cleaned.csv"
df.to_csv(file_path, index=False)

print("Export successful: Compass_Data_1_Cleaned.csv has been created in the output folder.")

Export successful: Compass_Data_1_Cleaned.csv has been created in the output folder.