#### Importing Libraries

In [1]:
import pandas as pd
from IPython.display import display
import numpy as np
import os

#### Loading and Viewing CSV from output folder

In [2]:
df = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/output/Compass_Data_1_Cleaned.csv")
display(df.sample(5))

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\IPython\core\interactiveshell.py:3166: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min),Battalion
13899,2026-08-28,08:29:49,0.0,2627164,No incident found on arrival at dispatch address,600 - Good Intent Call,35.912342,-78.933723,C,18,2.0,Engine,8.133333,1.466667,6.316667,3
16309,2026-08-21,00:44:18,0.0,2626334,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.996304,-78.890991,A,1,1.0,"Medical & rescue unit, other",4.200000,6.050000,10.116667,1
17748,2026-03-18,06:38:38,0.0,2608506,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.942593,-78.916351,B,4,1.0,Engine,8.883333,15.900000,24.600000,1
21737,2025-10-10,10:56:32,0.0,2532400,Extrication of victim(s) from vehicle,300 - Rescue & EMS,35.934555,-78.821442,C,13,7.0,Engine,7.450000,30.100000,34.933333,4
13261,2026-07-31,19:27:49,0.0,2623941,Removal of victim(s) from stalled elevator,300 - Rescue & EMS,36.064507,-78.904785,C,7,2.0,Truck or aerial,4.516667,34.316667,38.000000,2

In [3]:
df = df.drop(columns=["Alarm Date", "Alarm Time", "EMS Apparatus Count", "Incident Type", "Shift", 
                     "Suppression Apparatus Count", "Apparatus Type", "Total On Scene Time (min)",
                      "Total Time Alarm to Last Unit Cleared (min)", "Battalion"])
display(df.sample(5))

,Incident Number,Incident Type Group,Latitude,Longitude,Station,Dispatch Total Response Time (min)
13454,2624966,700 - False Alarm,35.998577,-78.905777,1,3.350000
21697,2615705,700 - False Alarm,35.891376,-78.906166,18,7.033333
19466,2622032,600 - Good Intent Call,35.925560,-78.832626,13,NaN
25961,2608281,700 - False Alarm,36.025372,-78.969147,10,8.750000
3355,2538066,300 - Rescue & EMS,36.041618,-78.876373,9,3.716667

#### Average Response Time by Incident Type Group

In [4]:
df["Dispatch Total Response Time (min)"] = pd.to_numeric(
    df["Dispatch Total Response Time (min)"],
    errors="coerce"
)

df_avg1 = df.groupby("Incident Type Group", as_index=False).agg({
    "Dispatch Total Response Time (min)": "mean"
})

df_avg1.columns = ["Incident Type Group", "Avg Response Time"]

display(df_avg1.head())

                               Incident Type Group  Avg Response Time
0                                       100 - Fire           6.594965
1  200 - Overpressure Rupture, Explosion, Overheat           6.459388
2                               300 - Rescue & EMS           6.162065
3                        400 - Hazardous Condition           7.321474
4                               500 - Service Call           7.941164

#### Average Response Time by Station

In [5]:
df["Dispatch Total Response Time (min)"] = pd.to_numeric(
    df["Dispatch Total Response Time (min)"],
    errors="coerce"
)

df_avg2 = df.groupby("Station", as_index=False).agg({
    "Dispatch Total Response Time (min)": "mean"
})

df_avg2.columns = ["Station", "Avg Response Time"]

display(df_avg2.head())

   Station  Avg Response Time
0        1           5.364082
1        2           6.313704
2        3           5.288258
3        4           6.146328
4        5           7.064627

#### Dropping Unwanted Columns & Exporting Files to Output Folder

In [6]:
df = df.drop(columns=["Station", "Dispatch Total Response Time (min)"])
display(df.sample(5))

# Ensuring output folder exists
os.makedirs("output", exist_ok=True)

# Exporting cleaned dataframe
file_path = "C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/output/Compass_Data_2_Cleaned.csv"
df.to_csv(file_path, index=False)
print("Export successful: Compass_Data_2_Cleaned.csv has been created in the output folder.")

# Exporting Average Response Time by Incident Type Group
file_path = "C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/output/Compass_Data_2a_Cleaned.csv"
df_avg1.to_csv(file_path, index=False)
print("Export successful: Compass_Data_2a_Cleaned.csv has been created in the output folder.")

# Exporting Average Response Time by Station
file_path = "C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/output/Compass_Data_2b_Cleaned.csv"
df_avg2.to_csv(file_path, index=False)
print("Export successful: Compass_Data_2b_Cleaned.csv has been created in the output folder.")

      Incident Number     Incident Type Group   Latitude  Longitude
7222          2616791  600 - Good Intent Call  35.925262 -78.889687
9009          2620802      300 - Rescue & EMS  36.015923 -78.888725
18537         2618446              100 - Fire  35.938889 -78.902992
23544         2620447  600 - Good Intent Call  35.986549 -78.841240
8553          2611589  600 - Good Intent Call  35.898178 -78.897430

Export successful: Compass_Data_2_Cleaned.csv has been created in the output folder.
Export successful: Compass_Data_2a_Cleaned.csv has been created in the output folder.
Export successful: Compass_Data_2b_Cleaned.csv has been created in the output folder.