#### Importing Libraries

In [47]:
import pandas as pd
from IPython.display import display
import numpy as np
import os

#### Loading and Viewing CSV from input folder

In [48]:
df = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/input/Compass_Data_1.csv")
display(df.sample(15))

,Alarm DateTime,Dispatch Total Response Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Total On Scene Time,Total Time Alarm to Last Unit Cleared,Apparatus Type
20436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other apparatus/resource
3442,2025-09-20 12:16:15.000,387.0,0.0,2530118,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.941746,-78.894821,B Shift,CAD Beat 04,1.0,949.0,1331.0,"Medical & rescue unit, other"
6801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine
27198,2025-09-02 18:58:36.000,377.0,0.0,2528088,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.988026,-78.919968,C Shift,CAD Beat 05,1.0,902.0,1272.0,Engine
28689,2025-10-27 22:16:27.000,442.0,0.0,2534536,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.972744,-78.907883,B Shift,CAD Beat 04,1.0,73.0,504.0,"Medical & rescue unit, other"
37964,2026-04-20 11:53:03.000,308.0,0.0,2612264,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.958542,-78.976532,A Shift,FS 11,2.0,394.0,685.0,Truck or aerial
47102,2025-10-23 08:41:44.000,321.0,0.0,2533937,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.059761,-78.931396,C Shift,CAD Beat 07,1.0,724.0,1015.0,"Medical & rescue unit, other"
57261,2025-08-30 15:39:47.000,326.0,0.0,2527743,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.949585,-78.877113,B Shift,CAD Beat 04,2.0,1710.0,2031.0,"Medical & rescue unit, other"
44077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Medical & rescue unit, other"
13108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chief officer car
48718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine
48764,2026-04-26 04:31:40.000,293.0,0.0,2612895,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.894821,-78.848915,B Shift,FS 19,1.0,846.0,1128.0,Engine
38312,2025-12-29 00:27:28.000,292.0,0.0,2541567,Passenger vehicle fire,100 - Fire,35.983788,-78.863144,B Shift,CAD Beat 03,7.0,19540.0,19740.0,Engine
54942,2025-09-27 16:15:02.000,281.0,0.0,2530932,"Smoke detector activation, no fire - unintenti...",700 - False Alarm,35.941544,-78.785347,B Shift,CAD Beat 17,2.0,215.0,427.0,Truck or aerial
41763,2026-04-27 13:38:51.000,511.0,0.0,2613049,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.883312,-78.887909,B Shift,FS 12,1.0,280.0,774.0,Engine

In [49]:
print(df.columns.tolist())

['Alarm DateTime', 'Dispatch Total Response Time', 'EMS Apparatus Count', 'Incident Number', 'Incident Type', 'Incident Type Group', 'Latitude', 'Longitude', 'Shift', 'Station', 'Suppression Apparatus Count', 'Total On Scene Time', 'Total Time Alarm to Last Unit Cleared', 'Apparatus Type']

#### Splitting Alarm Date Time to Alarm Date & Alarm Time

In [50]:
# Ensuring datetime type
df["Alarm DateTime"] = pd.to_datetime(df["Alarm DateTime"])

# Splitting into separate columns
df["Alarm Date"] = df["Alarm DateTime"].dt.date.astype(str)   # YYYY-MM-DD
df["Alarm Time"] = df["Alarm DateTime"].dt.time.astype(str)   # HH:MM:SS

# Dropping original column
df = df.drop(columns=["Alarm DateTime"])

# Moving new columns to the front
cols = ["Alarm Date", "Alarm Time"] + [c for c in df.columns if c not in ["Alarm Date", "Alarm Time"]]
df = df[cols]

display(df.sample(5))

,Alarm Date,Alarm Time,Dispatch Total Response Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Total On Scene Time,Total Time Alarm to Last Unit Cleared,Apparatus Type
51745,2025-08-03,11:33:50,353.0,0.0,2524589,"Outside rubbish fire, other",100 - Fire,36.005684,-78.903297,C Shift,CAD Beat 01,6.0,765.0,907.0,Chief officer car
30486,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HazMat unit
43648,2025-11-10,22:13:06,577.0,0.0,2536164,Carbon monoxide incident,400 - Hazardous Condition,36.009315,-78.944962,A Shift,CAD Beat 02,12.0,13870.0,14383.0,Engine
32247,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine
7861,2025-07-16,10:14:32,547.0,0.0,2522427,"Medical assist, assist EMS crew",300 - Rescue & EMS,0.000000,0.000000,B Shift,CAD Beat 03,1.0,1424.0,1971.0,"Medical & rescue unit, other"

#### Coverting Time to Decimal Minutes

In [51]:
df["Dispatch Total Response Time (min)"] = df["Dispatch Total Response Time"] / 60
df["Total On Scene Time (min)"] = df["Total On Scene Time"] / 60
df["Total Time Alarm to Last Unit Cleared (min)"] = df["Total Time Alarm to Last Unit Cleared"] / 60

# Dropping original columns
df = df.drop(columns=["Dispatch Total Response Time"])
df = df.drop(columns=["Total On Scene Time"])
df = df.drop(columns=["Total Time Alarm to Last Unit Cleared"])
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
15137,2026-04-05,21:04:57,0.0,2610590,"Carbon monoxide detector activation, no CO",700 - False Alarm,35.926739,-78.765358,A Shift,FS 17,1.0,Engine,7.733333,4.800000,10.433333
386,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other apparatus/resource,NaN,NaN,NaN
8115,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other apparatus/resource,NaN,NaN,NaN
11076,2025-10-15,03:18:01,0.0,2532939,Dispatched & canceled en route,600 - Good Intent Call,35.996002,-78.905853,B Shift,CAD Beat 01,2.0,"Medical & rescue unit, other",NaN,NaN,4.100000
47837,2025-06-01,15:32:08,0.0,2517159,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,0.000000,0.000000,B Shift,CAD Beat 03,1.0,Engine,2.700000,7.833333,10.533333

#### Dropping "Shift" from the Shift column

In [52]:
df["Shift"] = df["Shift"].str.strip().str.replace("Shift", "", regex=False)
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
8081,2025-06-14,16:20:04,0.0,2518655,Dispatched & canceled en route,600 - Good Intent Call,0.00000,0.000000,B,CAD Beat 01,1.0,Engine,NaN,NaN,1.700000
52502,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine,NaN,NaN,NaN
36725,2025-08-06,19:43:23,0.0,2524942,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.93145,-78.817329,B,CAD Beat 13,2.0,Engine,7.25,16.866667,23.783333
47672,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Medical & rescue unit, other",NaN,NaN,NaN
30080,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Medical & rescue unit, other",NaN,NaN,NaN

#### Dropping "FS" and "CAD Beat" from Station Column and any zero in front of the number e.g in 05

In [53]:
df["Station"] = (
    df["Station"]
    .astype(str)
    .str.strip()
    .str.replace("FS", "", regex=False)
    .str.replace("CAD Beat", "", regex=False)
    .str.replace(r"[^\d]", "", regex=True)   # keeping only digits
)

# Converting to numeric and force integer
df["Station"] = pd.to_numeric(df["Station"], errors="coerce")
df = df.dropna(subset=["Station"])
df["Station"] = df["Station"].astype(int)

display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
40095,2026-04-20,07:59:04,0.0,2612236,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.046665,-78.889595,A,7,1.0,Engine,8.600000,20.666667,29.083333
52292,2025-10-20,12:39:24,0.0,2533605,"Smoke detector activation, no fire - unintenti...",700 - False Alarm,35.950329,-78.934402,B,6,2.0,Truck or aerial,5.883333,2.883333,7.466667
54216,2026-04-06,15:25:07,0.0,2610677,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.972515,-78.888008,C,4,1.0,Engine,5.133333,7.833333,12.816667
58661,2026-05-11,19:36:32,0.0,2614644,No incident found on arrival at dispatch address,600 - Good Intent Call,35.895199,-78.873573,A,19,2.0,"Medical & rescue unit, other",7.166667,4.100000,8.316667
56620,2026-03-09,08:00:01,0.0,2607525,Citizen complaint,900 - Special Incident,36.012165,-78.892487,C,1,2.0,Engine,6.100000,10.150000,11.816667

#### Filtering out Stations that not Stations 1-19

In [54]:
# Converting Station to numeric (invalid values become NaN)
df["Station"] = pd.to_numeric(df["Station"], errors="coerce")

# Keeping only stations 1–19
df = df[df["Station"].between(1, 19)]

display(df.sample(5))

print("June rows:", pd.to_datetime(df["Alarm Date"], errors="coerce").dt.month.eq(6).sum())

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
23008,2025-06-22,10:08:03,0.0,2519504,"False alarm or false call, other",700 - False Alarm,0.000000,0.000000,B,6,2.0,Engine,4.766667,34.683333,39.450000
3433,2025-11-20,01:30:25,0.0,2537287,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.975437,-78.889206,B,4,2.0,"Medical & rescue unit, other",8.600000,40.200000,48.666667
22388,2025-07-27,15:58:44,0.0,2523745,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,0.000000,0.000000,C,11,2.0,Quint,4.500000,7.583333,12.083333
48690,2025-08-08,13:37:44,0.0,2525147,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.900204,-78.899597,A,12,1.0,Truck or aerial,7.350000,6.116667,12.866667
30781,2025-11-01,06:01:45,0.0,2535038,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.047665,-78.840088,B,1,1.0,Engine,6.450000,27.983333,34.000000

June rows: 2994

#### Adding Battalion Column

In [55]:
# Battalion mapping
battalion_map = {
    "1": 1,
    "2": 1,
    "3": 4,
    "4": 1,
    "5": 1,
    "6": 3,
    "7": 2,
    "8": 4,
    "9": 4,
    "10": 2,
    "11": 1,
    "12": 3,
    "13": 4,
    "14": 2,
    "15": 2,
    "16": 3,
    "17": 4,
    "18": 3,
    "19": 3
}

# Adding Battalion column
df["Battalion"] = df["Station"].astype(str).map(battalion_map)

display(df.sample(5))

print("June rows:", pd.to_datetime(df["Alarm Date"], errors="coerce").dt.month.eq(6).sum())

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min),Battalion
42542,2026-04-24,09:31:12,0.0,2612704,"Alarm system activation, no fire - unintentional",700 - False Alarm,35.965412,-78.911049,A,4,2.0,Truck or aerial,5.216667,4.700000,8.066667,1
44251,2025-06-30,19:34:41,0.0,2520586,"Alarm system activation, no fire - unintentional",700 - False Alarm,0.000000,0.000000,A,4,2.0,Engine,4.783333,8.683333,13.466667,1
26308,2026-01-21,22:41:53,0.0,2602436,"Person in distress, other",500 - Service Call,35.900204,-78.899597,C,12,1.0,Engine,9.500000,23.716667,29.700000,3
41573,2025-10-10,10:03:50,0.0,2532391,Rescue or EMS standby,300 - Rescue & EMS,35.940601,-78.992104,C,16,2.0,Quint,9.766667,2.933333,11.916667,3
19324,2026-02-27,12:21:46,0.0,2606474,Alarm system sounded due to malfunction,700 - False Alarm,36.095276,-78.917076,A,14,2.0,Truck or aerial,10.066667,9.300000,18.433333,2

June rows: 2994

#### Dropping blank rows of Apparatus Type

In [56]:
# Dropping rows where Apparatus Type is blank or null
df = df[
    df["Apparatus Type"].notna() &
    (df["Apparatus Type"].astype(str).str.strip() != "")
]

display(df.sample(5))

print("June rows:", pd.to_datetime(df["Alarm Date"], errors="coerce").dt.month.eq(6).sum())

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min),Battalion
37961,2026-02-10,16:30:34,0.0,2604585,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.987007,-78.900589,A,1,3.0,Chief officer car,3.433333,34.216667,37.450000,1
49236,2026-05-20,17:26:59,0.0,2615642,HazMat release investigation w/no HazMat,600 - Good Intent Call,35.965958,-78.948914,A,5,3.0,HazMat unit,15.733333,11.300000,25.516667,1
47911,2025-11-15,11:57:51,0.0,2536729,"Smoke detector activation, no fire - unintenti...",700 - False Alarm,35.894119,-78.920609,B,18,2.0,Truck or aerial,5.150000,2.883333,5.466667,3
23150,2025-10-25,23:55:59,0.0,2534304,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.035164,-78.907822,C,7,1.0,"Medical & rescue unit, other",4.533333,12.216667,16.616667,2
24279,2025-07-06,19:26:51,0.0,2521280,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,0.000000,0.000000,C,1,1.0,"Medical & rescue unit, other",6.066667,21.000000,27.066667,1

June rows: 2991

#### Exporting File to Output Folder

In [57]:
# Ensuring output folder exists
os.makedirs("output", exist_ok=True)

# Exporting cleaned dataframe
file_path = "C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/output/Compass_Data_1_Cleaned.csv"
df.to_csv(file_path, index=False)

print("Export successful: Compass_Data_1_Cleaned.csv has been created in the output folder.")

Export successful: Compass_Data_1_Cleaned.csv has been created in the output folder.