#### Importing Libraries

In [1]:
import pandas as pd
from IPython.display import display
import numpy as np
import os

#### Loading and Viewing CSV from input folder

In [2]:
df = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/input/Compass_Data_1.csv")
display(df.sample(15))

,Alarm DateTime,Dispatch Total Response Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Total On Scene Time,Total Time Alarm to Last Unit Cleared
9528,2026-03-28 20:17:01.000,341.0,0,2609719,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.983013,-78.904091,B Shift,FS 1,1,966.0,1303
18475,2025-12-11 18:22:47.000,315.0,0,2539636,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.982201,-78.902802,B Shift,CAD Beat 01,1,314.0,617
32482,2026-03-12 13:26:01.000,402.0,0,2607921,"Detector activation, no fire - unintentional",700 - False Alarm,35.868587,-78.835548,A Shift,FS 19,2,712.0,1023
25157,2026-05-24 09:20:39.000,247.0,0,2616025,Alarm system sounded due to malfunction,700 - False Alarm,36.008247,-78.910133,A Shift,FS 2,2,1652.0,1830
18909,2025-07-17 00:12:29.000,204.0,0,2522512,"Medical assist, assist EMS crew",300 - Rescue & EMS,0.000000,0.000000,B Shift,CAD Beat 01,1,203.0,407
4997,2026-04-21 13:32:13.000,460.0,0,2612396,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.985348,-78.901108,C Shift,FS 1,1,305.0,714
8415,2026-02-17 14:17:10.000,NaN,0,2605361,Dispatched & canceled en route,600 - Good Intent Call,36.032078,-78.916878,B Shift,FS 2,1,NaN,508
30020,2025-06-15 16:05:03.000,177.0,0,2518765,"Alarm system activation, no fire - unintentional",700 - False Alarm,0.000000,0.000000,A Shift,CAD Beat 04,1,692.0,869
20118,2026-05-19 14:28:08.000,294.0,0,2615507,"Detector activation, no fire - unintentional",700 - False Alarm,36.063690,-78.890495,C Shift,FS 7,2,304.0,516
25056,2025-06-24 19:28:46.000,223.0,0,2519806,"Trash or rubbish fire, contained",100 - Fire,0.000000,0.000000,A Shift,CAD Beat 14,6,353.0,576
17437,2025-12-14 11:25:02.000,416.0,0,2539926,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.891121,-78.884270,A Shift,CAD Beat 12,1,699.0,1093
26678,2025-12-29 07:25:53.000,159.0,0,2541582,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.954567,-78.892578,A Shift,CAD Beat 04,1,1228.0,1374
6979,2025-06-30 10:25:41.000,599.0,0,2520524,Water or steam leak,500 - Service Call,0.000000,0.000000,A Shift,CAD Beat 11,2,1850.0,2449
17875,2025-11-05 16:52:37.000,454.0,0,2535544,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.904663,-78.894142,C Shift,CAD Beat 12,1,1783.0,2208
20234,2025-08-01 04:46:11.000,NaN,0,2524329,Dispatched & canceled en route,600 - Good Intent Call,36.031746,-78.892036,B Shift,CAD Beat 07,1,NaN,356

In [3]:
print(df.columns.tolist())

['Alarm DateTime', 'Dispatch Total Response Time', 'EMS Apparatus Count', 'Incident Number', 'Incident Type', 'Incident Type Group', 'Latitude', 'Longitude', 'Shift', 'Station', 'Suppression Apparatus Count', 'Total On Scene Time', 'Total Time Alarm to Last Unit Cleared']

#### Splitting Alarm Date Time to Alarm Date & Alarm Time

In [4]:
# Ensuring datetime type
df["Alarm DateTime"] = pd.to_datetime(df["Alarm DateTime"])

# Splitting into separate columns
df["Alarm Date"] = df["Alarm DateTime"].dt.date.astype(str)   # YYYY-MM-DD
df["Alarm Time"] = df["Alarm DateTime"].dt.time.astype(str)   # HH:MM:SS

# Dropping original column
df = df.drop(columns=["Alarm DateTime"])

# Moving new columns to the front
cols = ["Alarm Date", "Alarm Time"] + [c for c in df.columns if c not in ["Alarm Date", "Alarm Time"]]
df = df[cols]

display(df.sample(5))

,Alarm Date,Alarm Time,Dispatch Total Response Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Total On Scene Time,Total Time Alarm to Last Unit Cleared
11644,2026-02-17,12:36:18,400.0,0,2605348,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.936142,-78.899025,B Shift,FS 4,1,1003.0,1360
23811,2025-11-14,13:20:58,331.0,0,2536624,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.041965,-78.915977,A Shift,CAD Beat 07,1,1152.0,1439
20539,2025-11-13,17:45:08,724.0,0,2536542,"Carbon monoxide detector activation, no CO",700 - False Alarm,35.910568,-78.948669,B Shift,CAD Beat 18,1,665.0,1244
33122,2025-07-19,16:05:46,311.0,0,2522814,"Vehicle accident, general cleanup",400 - Hazardous Condition,0.000000,0.000000,C Shift,CAD Beat 07,2,243.0,554
20932,2025-09-02,01:44:29,NaN,0,2528002,Dispatched & canceled en route,600 - Good Intent Call,35.904541,-78.904655,B Shift,CAD Beat 18,1,NaN,298

#### Coverting Time to Decimal Minutes

In [5]:
df["Dispatch Total Response Time (min)"] = df["Dispatch Total Response Time"] / 60
df["Total On Scene Time (min)"] = df["Total On Scene Time"] / 60
df["Total Time Alarm to Last Unit Cleared (min)"] = df["Total Time Alarm to Last Unit Cleared"] / 60

# Dropping original columns
df = df.drop(columns=["Dispatch Total Response Time"])
df = df.drop(columns=["Total On Scene Time"])
df = df.drop(columns=["Total Time Alarm to Last Unit Cleared"])
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
6517,2026-03-03,17:24:28,0,2606871,Alarm system sounded due to malfunction,700 - False Alarm,35.999035,-78.938049,C Shift,FS 5,4,10.983333,25.366667,34.500000
22696,2026-03-27,16:15:24,0,2609600,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.903126,-78.907333,A Shift,FS 18,1,6.366667,1.333333,7.500000
5149,2025-12-24,21:37:07,0,2541129,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.957764,-78.825989,C Shift,CAD Beat 08,1,11.550000,18.350000,29.700000
13758,2025-08-01,12:43:41,0,2524376,Gas leak (natural gas or LPG),400 - Hazardous Condition,35.915440,-78.941162,A Shift,CAD Beat 18,1,5.000000,25.816667,29.500000
16729,2025-08-14,13:15:39,0,2525814,CO detector activation due to malfunction,700 - False Alarm,35.868465,-78.855598,A Shift,CAD Beat 19,1,1.450000,15.350000,15.933333

#### Dropping "Shift" from the Shift column

In [6]:
df["Shift"] = df["Shift"].str.strip().str.replace("Shift", "", regex=False)
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
25238,2025-08-17,02:24:56,0,2526109,Dispatched & canceled en route,600 - Good Intent Call,35.986111,-78.882103,A,CAD Beat 03,1,NaN,NaN,5.300000
4935,2026-04-26,13:45:00,0,2612947,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.030148,-78.982269,A,FS 10,1,6.316667,26.583333,32.483333
28632,2025-10-18,07:43:34,0,2533369,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.908298,-78.985359,B,CAD Beat 16,1,2.583333,18.533333,20.833333
17818,2025-09-09,15:16:11,0,2528910,Gas leak (natural gas or LPG),400 - Hazardous Condition,35.996189,-78.873589,A,CAD Beat 03,1,3.200000,81.200000,82.583333
9797,2026-02-03,11:12:32,0,2603755,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.069328,-78.933609,C,FS 14,1,3.483333,20.883333,24.250000

#### Dropping "FS" and "CAD Beat" from Station Column and any zero in front of the number e.g in 05

In [7]:
df["Station"] = (
    df["Station"]
    .str.strip()
    .str.replace("FS", "", regex=False)
    .str.replace("CAD Beat", "", regex=False)
    .str.replace(r"\b0+(\d+)\b", r"\1", regex=True)
)

display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
13301,2026-02-10,18:30:07,0,2604597,"Excessive heat, scorch burns with no ignition","200 - Overpressure Rupture, Explosion, Overheat",35.940498,-78.992264,A,16,4,10.900000,12.466667,21.133333
17482,2025-08-06,06:08:00,0,2524867,Motor vehicle accident with no injuries.,300 - Rescue & EMS,36.051224,-78.905403,C,7,3,6.016667,15.416667,17.933333
19576,2025-10-21,01:52:46,0,2533699,Alarm system sounded due to malfunction,700 - False Alarm,35.973400,-78.895889,B,4,2,6.350000,2.016667,6.850000
19416,2025-10-03,19:56:48,0,2531643,HazMat release investigation w/no HazMat,600 - Good Intent Call,35.951286,-78.907982,B,4,1,11.566667,11.966667,22.750000
24318,2026-05-22,11:08:16,0,2615848,"Alarm system activation, no fire - unintentional",700 - False Alarm,36.011555,-78.945625,A,2,2,8.533333,7.233333,13.416667

#### Exporting File to Output Folder

In [8]:
# Ensuring output folder exists
os.makedirs("output", exist_ok=True)

# Exporting cleaned dataframe
file_path = "C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/output/Compass_Data_1_Cleaned.csv"
df.to_csv(file_path, index=False)

print("Export successful: Compass_Data_1_Cleaned.csv has been created in the output folder.")

Export successful: Compass_Data_1_Cleaned.csv has been created in the output folder.