#### Importing Libraries

In [46]:
import pandas as pd
from IPython.display import display
import numpy as np
import os

#### Loading and Viewing CSV from output folder

In [47]:
df = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/output/Compass_Data_1_Cleaned.csv")
display(df.sample(5))

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\IPython\core\interactiveshell.py:3166: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min),Battalion
7697,2025-10-30,12:02:54,0.0,2534846,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.904793,-78.937508,A,18,1.0,Engine,3.583333,17.400000,20.333333,3
25663,2025-11-24,10:38:49,0.0,2537762,"Alarm system activation, no fire - unintentional",700 - False Alarm,35.996223,-78.902130,C,1,4.0,Chief officer car,5.050000,9.966667,13.733333,1
33099,2025-08-19,09:48:56,0.0,2526386,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.030167,-78.869568,B,9,1.0,Engine,3.700000,23.616667,27.033333,4
27437,2026-03-30,17:22:36,0.0,2609895,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.894821,-78.848915,B,19,1.0,Engine,3.766667,29.150000,32.850000,3
7105,2026-03-01,17:05:59,0.0,2606689,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.010246,-78.920372,C,2,1.0,Engine,2.733333,31.100000,33.666667,1

In [48]:
df = df.drop(columns=["Alarm Date", "Alarm Time", "EMS Apparatus Count", "Incident Type", "Shift", 
                     "Suppression Apparatus Count", "Apparatus Type", "Total On Scene Time (min)",
                      "Total Time Alarm to Last Unit Cleared (min)"])
display(df.sample(5))

,Incident Number,Incident Type Group,Latitude,Longitude,Station,Dispatch Total Response Time (min),Battalion
24260,2602498,700 - False Alarm,35.918308,-78.845680,13,4.800000,4
9864,2532277,500 - Service Call,36.009514,-78.941925,2,3.750000,1
32499,2532572,600 - Good Intent Call,35.972900,-78.782471,1,NaN,1
29550,2529823,300 - Rescue & EMS,35.987919,-78.930939,5,5.366667,1
897,2613232,300 - Rescue & EMS,36.029484,-78.899162,7,6.216667,2

#### Loading and Viewing CSV from input folder

In [49]:
df2 = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/input/Fire_Stations_Geocoded 1.csv")
display(df2.sample(5))

,Station,Battalion,Physical.Location,lat,long
11,Station 12,3,"1230 Carpenter Fletcher Road Durham, NC 27713",35.915234,-78.897464
14,Station 15,2,"2060 Torredge Road Durham, NC 27712",36.098238,-78.867640
0,Station 1,1,"139 E. Morgan Street Durham, NC 27701",35.996845,-78.897998
18,Station 19,3,"4716 Old Page Road Durham, NC 27703",35.883820,-78.846571
3,Station 4,1,"1818 Riddle Road Durham, NC 27713",35.955776,-78.889658

In [50]:
df2 = df2.rename(columns={
    "lat": "Station lat",
    "long": "Station long"
})
df2 = df2.drop(columns=["Physical.Location", "Battalion"])

display(df2.sample(5))

       Station  Station lat  Station long
17  Station 18    35.898550    -78.926548
4    Station 5    35.983517    -78.930987
16  Station 17    35.941071    -78.796138
15  Station 16    35.905729    -78.982744
5    Station 6    35.933531    -78.951136

#### df3 = df2 + df

In [51]:
df2["Station"] = df2["Station"].str.replace("Station", "", regex=False).str.strip().astype(int)
df3 = df.merge(
    df2[["Station", "Station lat", "Station long"]],
    on="Station",
    how="left"
)
display(df3.sample(5))

,Incident Number,Incident Type Group,Latitude,Longitude,Station,Dispatch Total Response Time (min),Battalion,Station lat,Station long
6334,2535624,300 - Rescue & EMS,36.046665,-78.889595,7,3.750000,2,36.054402,-78.904624
10111,2603520,500 - Service Call,35.978706,-78.884804,4,12.316667,1,35.955776,-78.889658
15528,2523073,300 - Rescue & EMS,0.000000,0.000000,3,5.066667,4,35.990902,-78.867037
4262,2615538,300 - Rescue & EMS,36.003651,-78.901703,1,4.016667,1,35.996845,-78.897998
10619,2603820,300 - Rescue & EMS,35.919113,-78.912346,12,6.416667,3,35.915234,-78.897464

#### Exporting File to Output Folder

In [52]:
# Ensuring output folder exists
os.makedirs("output", exist_ok=True)

# Exporting cleaned dataframe
file_path = "C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/output/Compass_Data_2_Cleaned.csv"
df3.to_csv(file_path, index=False)

print("Export successful: Compass_Data_2_Cleaned.csv has been created in the output folder.")

Export successful: Compass_Data_2_Cleaned.csv has been created in the output folder.