#### Importing Libraries

In [49]:
import pandas as pd
from IPython.display import display
import numpy as np
import os

#### Loading and Viewing CSV from input folder

In [50]:
df = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/input/Compass_Data_1.csv")
display(df.sample(15))

,Alarm DateTime,Dispatch Total Response Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Total On Scene Time,Total Time Alarm to Last Unit Cleared
22445,2025-11-12 19:11:13.000,470.0,0,2536411,Motor vehicle accident with no injuries.,300 - Rescue & EMS,35.894684,-78.857567,A Shift,CAD Beat 19,2,1234.0,1481
27864,2025-07-01 02:23:56.000,386.0,0,2520623,Rescue or EMS standby,300 - Rescue & EMS,0.000000,0.000000,A Shift,CAD Beat 07,1,170.0,556
20015,2025-06-03 20:47:42.000,414.0,0,2517437,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,0.000000,0.000000,B Shift,CAD Beat 06,1,791.0,1205
9519,2026-04-14 12:29:09.000,349.0,0,2611575,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.001568,-78.836052,B Shift,FS 8,1,101.0,430
25405,2026-03-20 17:38:21.000,641.0,0,2608810,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.900703,-78.822662,C Shift,FS 13,1,1058.0,1536
28458,2025-11-10 03:23:36.000,368.0,0,2536057,Building fire,100 - Fire,35.970425,-78.911324,C Shift,CAD Beat 04,14,13202.0,13489
18612,2025-09-03 22:44:55.000,257.0,0,2528219,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.926846,-78.832222,B Shift,CAD Beat 13,1,820.0,1067
12242,2025-05-29 14:24:24.000,NaN,0,2516804,Dispatched & canceled en route,600 - Good Intent Call,0.000000,0.000000,A Shift,CAD Beat 11,2,NaN,231
3939,2026-04-15 14:34:50.000,175.0,0,2611685,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.983261,-78.931091,C Shift,FS 5,4,391.0,560
27585,2026-03-29 18:07:44.000,291.0,0,2609801,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.933441,-78.966736,A Shift,FS 6,1,548.0,819
6285,2026-02-07 21:02:19.000,206.0,0,2604256,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.001289,-78.898193,C Shift,FS 1,1,501.0,689
16017,2025-08-14 18:42:27.000,237.0,0,2525849,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.004742,-78.854797,A Shift,CAD Beat 09,1,652.0,876
25511,2025-06-02 15:13:39.000,NaN,0,2517280,Dispatched & canceled en route,600 - Good Intent Call,0.000000,0.000000,A Shift,CAD Beat 04,1,NaN,443
15527,2026-04-24 12:16:15.000,NaN,0,2612724,Dispatched & canceled en route,600 - Good Intent Call,36.049061,-78.920525,A Shift,FS 7,3,NaN,385
32476,2025-06-12 13:00:04.000,415.0,0,2518397,Alarm system sounded due to malfunction,700 - False Alarm,0.000000,0.000000,C Shift,CAD Beat 01,6,1452.0,1867

In [51]:
print(df.columns.tolist())

['Alarm DateTime', 'Dispatch Total Response Time', 'EMS Apparatus Count', 'Incident Number', 'Incident Type', 'Incident Type Group', 'Latitude', 'Longitude', 'Shift', 'Station', 'Suppression Apparatus Count', 'Total On Scene Time', 'Total Time Alarm to Last Unit Cleared']

#### Splitting Alarm Date Time to Alarm Date & Alarm Time

In [52]:
# Ensuring datetime type
df["Alarm DateTime"] = pd.to_datetime(df["Alarm DateTime"])

# Splitting into separate columns
df["Alarm Date"] = df["Alarm DateTime"].dt.date.astype(str)   # YYYY-MM-DD
df["Alarm Time"] = df["Alarm DateTime"].dt.time.astype(str)   # HH:MM:SS

# Dropping original column
df = df.drop(columns=["Alarm DateTime"])

# Moving new columns to the front
cols = ["Alarm Date", "Alarm Time"] + [c for c in df.columns if c not in ["Alarm Date", "Alarm Time"]]
df = df[cols]

display(df.sample(5))

,Alarm Date,Alarm Time,Dispatch Total Response Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Total On Scene Time,Total Time Alarm to Last Unit Cleared
4171,2025-12-21,18:47:46,604.0,0,2540792,"Service Call, other",500 - Service Call,36.119194,-78.870041,A Shift,CAD Beat 15,1,1076.0,1680
33762,2025-06-29,23:28:26,394.0,0,2520483,"Medical assist, assist EMS crew",300 - Rescue & EMS,0.000000,0.000000,B Shift,CAD Beat 04,1,139.0,533
31716,2025-11-26,10:54:01,269.0,0,2537963,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.893070,-78.845306,B Shift,CAD Beat 19,1,862.0,1118
6234,2025-06-25,15:30:43,371.0,0,2519937,Heat detector activation due to malfunction,700 - False Alarm,0.000000,0.000000,C Shift,CAD Beat 18,2,562.0,933
2963,2025-10-28,16:46:24,570.0,0,2534624,Authorized controlled burning,600 - Good Intent Call,35.982918,-78.898857,A Shift,CAD Beat 01,2,228.0,657

#### Coverting Time to Decimal Minutes

In [53]:
df["Dispatch Total Response Time (min)"] = df["Dispatch Total Response Time"] / 60
df["Total On Scene Time (min)"] = df["Total On Scene Time"] / 60
df["Total Time Alarm to Last Unit Cleared (min)"] = df["Total Time Alarm to Last Unit Cleared"] / 60

# Dropping original columns
df = df.drop(columns=["Dispatch Total Response Time"])
df = df.drop(columns=["Total On Scene Time"])
df = df.drop(columns=["Total Time Alarm to Last Unit Cleared"])
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
2191,2025-09-22,21:33:52,0,2530396,"Outside rubbish, trash or waste fire",100 - Fire,35.982502,-78.900558,A Shift,CAD Beat 01,11,3.150000,17.650000,19.716667
5141,2026-04-04,15:28:40,0,2610450,"Smoke detector activation, no fire - unintenti...",700 - False Alarm,35.913528,-78.985847,C Shift,FS 16,2,3.700000,9.883333,12.466667
31611,2025-05-25,16:09:26,0,2516386,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,0.000000,0.000000,A Shift,CAD Beat 07,1,4.116667,19.500000,23.616667
21328,2025-10-17,22:43:41,1,2533334,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.904194,-78.941780,C Shift,CAD Beat 18,1,10.216667,3.100000,13.200000
16507,2025-06-24,22:30:28,0,2519822,Dispatched & canceled en route,600 - Good Intent Call,0.000000,0.000000,A Shift,CAD Beat 13,1,NaN,NaN,5.683333

#### Dropping "Shift" from the Shift column

In [54]:
df["Shift"] = df["Shift"].str.strip().str.replace("Shift", "", regex=False)
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
4682,2026-02-11,10:53:49,0,2604668,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.055626,-78.915916,B,FS 7,1,3.750000,14.133333,17.500000
19091,2025-12-13,00:13:27,0,2539775,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.991123,-78.907707,A,CAD Beat 05,2,5.016667,11.683333,16.483333
22676,2025-09-02,08:40:23,0,2528029,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.958286,-78.853210,C,CAD Beat 13,1,5.100000,42.883333,47.733333
25492,2025-11-23,03:06:39,0,2537614,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.002789,-78.956696,C,CAD Beat 11,1,7.816667,9.366667,16.966667
3159,2025-08-08,11:40:19,0,2525129,Alarm system sounded due to malfunction,700 - False Alarm,35.900406,-78.842445,A,CAD Beat 19,5,7.583333,18.466667,24.616667

#### Exporting File to Output Folder

In [55]:
# Ensuring output folder exists
os.makedirs("output", exist_ok=True)

# Exporting cleaned dataframe
file_path = "C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/output/Compass_Data_1_Cleaned.csv"
df.to_csv(file_path, index=False)

print("Export successful: Compass_Data_1_Cleaned.csv has been created in the output folder.")

Export successful: Compass_Data_1_Cleaned.csv has been created in the output folder.