#### Importing Libraries

In [32]:
import pandas as pd
from IPython.display import display
import numpy as np
import os

#### Loading and Viewing CSV from input folder

In [33]:
df = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/input/Compass_Data_1.csv")
display(df.sample(15))

,Alarm DateTime,Dispatch Total Response Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Total On Scene Time,Total Time Alarm to Last Unit Cleared,Apparatus Type
12539,2025-09-22 23:43:11.000,356.0,0.0,2530404,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.982620,-78.834839,A Shift,CAD Beat 08,1.0,1222.0,1562.0,Engine
30462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Truck or aerial
27962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Breathing apparatus support
16813,2025-08-14 12:05:31.000,370.0,0.0,2525799,Alarm system sounded due to malfunction,700 - False Alarm,35.972466,-78.890076,A Shift,CAD Beat 04,2.0,1152.0,1439.0,Engine
31489,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine
36827,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine
14199,2025-12-12 12:15:57.000,321.0,0.0,2539709,Alarm system sounded due to malfunction,700 - False Alarm,35.948048,-78.871193,A Shift,CAD Beat 04,2.0,2269.0,2512.0,Engine
37271,2025-12-24 17:39:51.000,374.0,0.0,2541104,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.009575,-78.850464,C Shift,CAD Beat 09,1.0,980.0,1347.0,Engine
34789,2026-05-18 13:04:48.000,301.0,0.0,2615392,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.036911,-78.938950,B Shift,FS 10,1.0,554.0,818.0,Engine
44389,2026-06-20 17:51:29.000,470.0,0.0,2619199,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.046745,-78.937401,C Shift,FS 10,1.0,248.0,659.0,Engine
59655,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Truck or aerial
59372,2025-11-26 14:06:28.000,683.0,0.0,2537992,Motor vehicle accident with injuries,300 - Rescue & EMS,35.933716,-78.989128,B Shift,CAD Beat 16,2.0,3189.0,3697.0,Engine
44645,2025-11-19 02:50:29.000,242.0,0.0,2537163,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.888039,-78.848473,C Shift,CAD Beat 19,1.0,674.0,902.0,Engine
21655,2025-11-22 18:24:40.000,489.0,0.0,2537588,HazMat release investigation w/no HazMat,600 - Good Intent Call,35.910328,-78.927139,C Shift,CAD Beat 18,4.0,651.0,1028.0,Engine
13697,2025-12-10 11:47:26.000,289.0,0.0,2539470,"Detector activation, no fire - unintentional",700 - False Alarm,35.990757,-78.908333,A Shift,CAD Beat 05,5.0,326.0,520.0,Engine

In [34]:
print(df.columns.tolist())

['Alarm DateTime', 'Dispatch Total Response Time', 'EMS Apparatus Count', 'Incident Number', 'Incident Type', 'Incident Type Group', 'Latitude', 'Longitude', 'Shift', 'Station', 'Suppression Apparatus Count', 'Total On Scene Time', 'Total Time Alarm to Last Unit Cleared', 'Apparatus Type']

#### Splitting Alarm Date Time to Alarm Date & Alarm Time

In [35]:
# Ensuring datetime type
df["Alarm DateTime"] = pd.to_datetime(df["Alarm DateTime"])

# Splitting into separate columns
df["Alarm Date"] = df["Alarm DateTime"].dt.date.astype(str)   # YYYY-MM-DD
df["Alarm Time"] = df["Alarm DateTime"].dt.time.astype(str)   # HH:MM:SS

# Dropping original column
df = df.drop(columns=["Alarm DateTime"])

# Moving new columns to the front
cols = ["Alarm Date", "Alarm Time"] + [c for c in df.columns if c not in ["Alarm Date", "Alarm Time"]]
df = df[cols]

display(df.sample(5))

,Alarm Date,Alarm Time,Dispatch Total Response Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Total On Scene Time,Total Time Alarm to Last Unit Cleared,Apparatus Type
1588,2026-07-29,02:18:11,274.0,0.0,2623620,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.996864,-78.910416,B Shift,FS 5,1.0,353.0,606.0,"Medical & rescue unit, other"
61783,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other apparatus/resource
4348,2025-09-14,16:13:21,255.0,0.0,2529450,"Smoke detector activation, no fire - unintenti...",700 - False Alarm,35.975101,-78.919144,B Shift,CAD Beat 05,2.0,117.0,364.0,Engine
8214,2026-06-29,20:18:03,339.0,0.0,2620228,No incident found on arrival at dispatch address,600 - Good Intent Call,35.932503,-78.915161,C Shift,FS 4,1.0,67.0,330.0,Engine
56441,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine

#### Coverting Time to Decimal Minutes

In [36]:
df["Dispatch Total Response Time (min)"] = df["Dispatch Total Response Time"] / 60
df["Total On Scene Time (min)"] = df["Total On Scene Time"] / 60
df["Total Time Alarm to Last Unit Cleared (min)"] = df["Total Time Alarm to Last Unit Cleared"] / 60

# Dropping original columns
df = df.drop(columns=["Dispatch Total Response Time"])
df = df.drop(columns=["Total On Scene Time"])
df = df.drop(columns=["Total Time Alarm to Last Unit Cleared"])
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
27904,2026-04-11,02:29:59,0.0,2611197,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.028381,-78.844543,B Shift,FS 9,1.0,Engine,7.283333,12.216667,19.266667
37768,2026-02-09,10:03:52,0.0,2604425,Dispatched & canceled en route,600 - Good Intent Call,35.938110,-78.739494,B Shift,NaN,1.0,Engine,NaN,NaN,0.916667
51699,2026-06-07,13:10:34,0.0,2617622,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.885281,-78.886879,C Shift,FS 12,1.0,"Medical & rescue unit, other",10.650000,3.350000,13.950000
21421,2025-08-15,04:18:27,0.0,2525899,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.999859,-78.938049,A Shift,CAD Beat 05,1.0,Engine,8.300000,16.416667,24.300000
42775,2025-12-18,05:53:10,0.0,2540358,"Arcing, shorted electrical equipment",400 - Hazardous Condition,35.931644,-78.895607,B Shift,CAD Beat 12,6.0,"Medical & rescue unit, other",6.650000,54.000000,58.583333

#### Dropping "Shift" from the Shift column

In [37]:
df["Shift"] = df["Shift"].str.strip().str.replace("Shift", "", regex=False)
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
1909,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine,NaN,NaN,NaN
44217,2026-04-23,14:48:33,0.0,2612626,Police matter,500 - Service Call,36.059635,-78.873413,C,FS 7,1.0,Engine,9.616667,67.483333,76.700000
9861,2025-11-26,22:54:48,0.0,2538039,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.953602,-78.906532,B,CAD Beat 04,1.0,"Medical & rescue unit, other",6.216667,4.550000,10.483333
53847,2026-03-13,22:49:54,0.0,2608094,HazMat release investigation w/no HazMat,600 - Good Intent Call,36.001945,-78.899429,B,FS 1,11.0,Other apparatus/resource,4.050000,15.783333,18.133333
44636,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine,NaN,NaN,NaN

#### Dropping "FS" and "CAD Beat" from Station Column and any zero in front of the number e.g in 05

In [38]:
df["Station"] = (
    df["Station"]
    .astype(str)
    .str.strip()
    .str.replace("FS", "", regex=False)
    .str.replace("CAD Beat", "", regex=False)
    .str.replace(r"[^\d]", "", regex=True)   # keeping only digits
)

# Converting to numeric and force integer
df["Station"] = pd.to_numeric(df["Station"], errors="coerce")
df = df.dropna(subset=["Station"])
df["Station"] = df["Station"].astype(int)

display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
60574,2026-06-27,02:28:53,0.0,2619901,Motor vehicle accident with injuries,300 - Rescue & EMS,36.005116,-78.866920,B,9,1.0,Engine,6.100000,21.100000,25.833333
27453,2025-10-08,19:38:14,0.0,2532217,"Alarm system activation, no fire - unintentional",700 - False Alarm,35.975250,-78.902306,C,4,2.0,Truck or aerial,5.066667,28.783333,33.183333
16629,2026-03-26,19:06:24,0.0,2609501,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.093575,-78.930412,B,14,1.0,Engine,4.333333,26.466667,30.616667
11896,2025-10-02,01:49:15,0.0,2531420,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.029781,-78.923485,B,2,1.0,Quint,8.533333,25.000000,33.150000
30276,2025-11-06,03:09:43,0.0,2535603,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.993523,-78.895889,C,1,1.0,Engine,3.483333,5.133333,8.533333

#### Filtering out Stations that not Stations 1-19

In [39]:
# Converting Station to numeric (invalid values become NaN)
df["Station"] = pd.to_numeric(df["Station"], errors="coerce")

# Save rows before filtering
df_before = df.copy()

# Keeping only stations 1–19
df = df[df["Station"].between(1, 19)]

# Get dropped rows
dropped_rows = df_before[~df_before.index.isin(df.index)]

print(f"Rows dropped: {len(dropped_rows)}")
print(f"Rows remaining: {len(df)}")

display(dropped_rows)

Rows dropped: 21
Rows remaining: 33030

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
1684,2025-10-28,18:03:58,0.0,2534634,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.930702,-78.896523,A,54,1.0,"Medical & rescue unit, other",6.616667,6.416667,12.116667
10038,2025-11-23,07:28:34,0.0,2537625,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.929741,-78.910950,A,54,1.0,"Medical & rescue unit, other",5.983333,19.316667,24.666667
10443,2025-10-26,14:45:23,0.0,2534367,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.932808,-78.896820,A,54,1.0,"Medical & rescue unit, other",5.216667,11.783333,16.883333
14734,2025-10-09,13:25:58,0.0,2532295,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.965271,-78.914734,A,54,1.0,"Medical & rescue unit, other",6.116667,0.683333,6.416667
17490,2025-08-25,12:00:57,0.0,2527123,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.927223,-78.897598,A,54,1.0,"Medical & rescue unit, other",5.766667,9.666667,15.216667
21880,2025-10-29,01:34:39,0.0,2534674,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.967148,-78.916145,A,54,1.0,"Medical & rescue unit, other",6.333333,26.466667,32.583333
24007,2025-08-31,12:03:07,0.0,2527826,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.930305,-78.895172,A,54,1.0,"Medical & rescue unit, other",5.516667,7.950000,13.366667
25281,2025-11-24,06:21:17,0.0,2537743,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.965271,-78.914734,A,54,1.0,"Medical & rescue unit, other",6.716667,23.200000,29.566667
28774,2025-11-23,08:14:48,0.0,2537630,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.929741,-78.910950,A,54,2.0,Engine,4.983333,15.800000,20.733333
29918,2025-10-26,13:42:42,0.0,2534364,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.965252,-78.916977,A,54,1.0,"Medical & rescue unit, other",5.600000,4.600000,9.900000
30377,2025-09-07,09:23:26,0.0,2528652,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.966125,-78.918388,A,54,1.0,"Medical & rescue unit, other",4.266667,8.166667,12.233333
33833,2025-11-08,09:24:56,0.0,2535857,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.931686,-78.913116,A,54,1.0,"Medical & rescue unit, other",6.566667,16.166667,22.683333
34664,2025-10-07,13:30:18,0.0,2532072,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.964516,-78.917519,A,54,1.0,"Medical & rescue unit, other",5.150000,19.983333,24.766667
34700,2025-09-07,10:19:47,0.0,2528658,Dispatched & canceled en route,600 - Good Intent Call,35.966125,-78.918388,A,54,1.0,"Medical & rescue unit, other",NaN,NaN,0.666667
35913,2025-12-10,18:54:10,0.0,2539528,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.930115,-78.914650,A,54,1.0,"Medical & rescue unit, other",5.383333,13.700000,19.033333
37967,2025-09-08,00:19:43,0.0,2528721,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.966125,-78.918388,A,54,1.0,"Medical & rescue unit, other",5.766667,21.683333,27.200000
43731,2025-09-16,04:19:51,0.0,2529626,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.929447,-78.920219,A,54,1.0,"Medical & rescue unit, other",6.150000,15.800000,21.800000
47002,2025-12-10,10:24:44,0.0,2539461,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.968483,-78.920235,A,54,1.0,"Medical & rescue unit, other",7.183333,5.850000,12.916667
47501,2025-12-10,15:54:47,0.0,2539503,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.964607,-78.854332,A,54,1.0,"Medical & rescue unit, other",7.666667,25.033333,31.866667
59934,2025-09-09,19:54:25,0.0,2528937,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.964619,-78.917671,A,54,1.0,"Medical & rescue unit, other",5.816667,2.550000,8.216667
61107,2025-10-28,08:12:52,0.0,2534566,Motor vehicle accident with no injuries.,300 - Rescue & EMS,35.935699,-78.921738,A,54,2.0,Engine,5.600000,5.383333,10.600000

In [40]:
# Displaying Remaining Rows
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
18172,2026-06-28,20:24:09,0.0,2620110,No incident found on arrival at dispatch address,600 - Good Intent Call,35.991180,-78.907372,B,1,1.0,"Medical & rescue unit, other",3.700000,3.250000,6.816667
13296,2026-01-27,06:45:35,0.0,2602928,"Carbon monoxide detector activation, no CO",700 - False Alarm,35.992168,-78.836487,A,8,1.0,Quint,10.550000,8.516667,17.550000
38828,2026-05-29,22:29:36,0.0,2616675,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.064507,-78.904785,B,7,1.0,Engine,4.333333,14.133333,18.400000
19664,2026-06-12,15:15:33,0.0,2618249,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.954674,-78.995110,A,16,1.0,Engine,8.083333,11.616667,19.283333
17704,2026-03-07,07:30:52,0.0,2607293,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.980488,-78.866692,C,3,1.0,Engine,3.866667,18.683333,22.233333

#### Adding Battalion Column

In [41]:
# Battalion mapping
battalion_map = {
    "1": 1,
    "2": 1,
    "3": 4,
    "4": 1,
    "5": 1,
    "6": 3,
    "7": 2,
    "8": 4,
    "9": 4,
    "10": 2,
    "11": 1,
    "12": 3,
    "13": 4,
    "14": 2,
    "15": 2,
    "16": 3,
    "17": 4,
    "18": 3,
    "19": 3
}

# Adding Battalion column
df["Battalion"] = df["Station"].astype(str).map(battalion_map)

display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min),Battalion
23398,2026-03-26,13:16:19,0.0,2609460,"Smoke detector activation, no fire - unintenti...",700 - False Alarm,35.951199,-78.996239,B,16,2.0,Engine,9.583333,3.583333,11.916667,3
20036,2026-06-26,19:24:09,0.0,2619873,Rescue or EMS standby,300 - Rescue & EMS,35.985691,-78.906685,B,1,1.0,Rescue unit,4.666667,7.933333,12.300000,1
6682,2026-02-18,21:16:52,0.0,2605537,Motor vehicle accident with no injuries.,300 - Rescue & EMS,36.023445,-78.918800,C,2,1.0,Engine,10.266667,11.300000,21.433333,1
15899,2026-03-27,17:10:35,0.0,2609604,"False alarm or false call, other",700 - False Alarm,35.937199,-78.928902,A,6,2.0,Engine,7.650000,1.166667,8.450000,3
18644,2026-02-05,19:50:00,0.0,2604010,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.960781,-78.996132,C,16,1.0,Engine,8.316667,16.216667,24.200000,3

#### Exporting File to Output Folder

In [42]:
# Ensuring output folder exists
os.makedirs("output", exist_ok=True)

# Exporting cleaned dataframe
file_path = "C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/output/Compass_Data_1_Cleaned.csv"
df.to_csv(file_path, index=False)

print("Export successful: Compass_Data_1_Cleaned.csv has been created in the output folder.")

Export successful: Compass_Data_1_Cleaned.csv has been created in the output folder.