#### Importing Libraries

In [56]:
import pandas as pd
from IPython.display import display
import numpy as np
import os

#### Loading and Viewing CSV from input folder

In [57]:
df = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/input/Compass_Data_1.csv")
display(df.sample(15))

,Alarm DateTime,Dispatch Total Response Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Total On Scene Time,Total Time Alarm to Last Unit Cleared
17130,2025-07-15 01:26:54.000,326.0,0,2522266,"Alarm system activation, no fire - unintentional",700 - False Alarm,0.000000,0.000000,B Shift,CAD Beat 02,4,1919.0,2245
30265,2026-04-29 19:56:36.000,263.0,0,2613284,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.933594,-78.833008,B Shift,FS 13,1,1043.0,1293
7746,2025-11-16 00:27:00.000,851.0,0,2536811,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.006104,-78.858772,B Shift,CAD Beat 09,1,200.0,1041
20102,2026-05-27 16:51:18.000,335.0,0,2616413,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.911789,-78.934563,B Shift,FS 18,1,570.0,846
7760,2025-07-07 17:22:14.000,439.0,0,2521416,No incident found on arrival at dispatch address,600 - Good Intent Call,0.000000,0.000000,B Shift,CAD Beat 07,1,274.0,713
12496,2025-09-28 17:58:25.000,286.0,0,2531041,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.897190,-79.008812,A Shift,CAD Beat DMOR,1,58.0,330
10930,2025-12-25 10:26:40.000,295.0,0,2541169,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.000019,-78.847939,A Shift,CAD Beat 03,2,4090.0,4365
19627,2025-06-20 02:23:51.000,NaN,0,2519286,Dispatched & canceled en route,600 - Good Intent Call,0.000000,0.000000,C Shift,CAD Beat 01,1,NaN,359
23062,2025-09-24 18:14:16.000,200.0,0,2530611,No incident found on arrival at dispatch address,600 - Good Intent Call,36.021027,-78.947861,A Shift,CAD Beat 02,2,166.0,246
18620,2026-04-19 01:12:32.000,438.0,0,2612108,Smoke detector activation due to malfunction,700 - False Alarm,35.945572,-78.863930,B Shift,FS 4,2,337.0,706
23128,2025-10-20 11:45:13.000,325.0,0,2533600,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.977993,-78.885361,B Shift,CAD Beat 04,4,2161.0,2460
32903,2025-11-09 09:18:10.000,327.0,0,2535967,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.926918,-78.909180,C Shift,CAD Beat 12,1,496.0,818
12383,2026-03-02 21:38:41.000,411.0,0,2606772,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.916241,-78.811035,B Shift,FS 13,1,2604.0,3002
3975,2025-10-26 18:55:34.000,213.0,0,2534395,"Alarm system activation, no fire - unintentional",700 - False Alarm,36.007298,-78.924789,A Shift,CAD Beat 02,2,273.0,382
19870,2025-08-01 15:17:39.000,341.0,0,2524391,Motor vehicle accident with no injuries.,300 - Rescue & EMS,35.942337,-78.899467,A Shift,CAD Beat 04,2,735.0,907

In [58]:
print(df.columns.tolist())

['Alarm DateTime', 'Dispatch Total Response Time', 'EMS Apparatus Count', 'Incident Number', 'Incident Type', 'Incident Type Group', 'Latitude', 'Longitude', 'Shift', 'Station', 'Suppression Apparatus Count', 'Total On Scene Time', 'Total Time Alarm to Last Unit Cleared']

#### Splitting Alarm Date Time to Alarm Date & Alarm Time

In [59]:
# Ensuring datetime type
df["Alarm DateTime"] = pd.to_datetime(df["Alarm DateTime"])

# Splitting into separate columns
df["Alarm Date"] = df["Alarm DateTime"].dt.date.astype(str)   # YYYY-MM-DD
df["Alarm Time"] = df["Alarm DateTime"].dt.time.astype(str)   # HH:MM:SS

# Dropping original column
df = df.drop(columns=["Alarm DateTime"])

# Moving new columns to the front
cols = ["Alarm Date", "Alarm Time"] + [c for c in df.columns if c not in ["Alarm Date", "Alarm Time"]]
df = df[cols]

display(df.sample(5))

,Alarm Date,Alarm Time,Dispatch Total Response Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Total On Scene Time,Total Time Alarm to Last Unit Cleared
24881,2026-02-15,11:54:57,594.0,0,2605105,No incident found on arrival at dispatch address,600 - Good Intent Call,35.988194,-78.933060,B Shift,FS 5,1,239.0,721
595,2026-02-19,11:04:36,415.0,0,2605599,"Alarm system activation, no fire - unintentional",700 - False Alarm,36.047298,-78.887695,A Shift,FS 7,2,145.0,522
21154,2025-08-23,19:24:43,254.0,0,2526933,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.043716,-78.890808,A Shift,CAD Beat 07,1,1699.0,1949
27168,2025-12-05,20:25:33,337.0,0,2539007,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.925610,-78.911438,C Shift,CAD Beat 12,1,953.0,1276
29611,2025-11-28,00:03:13,342.0,0,2538146,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.990810,-78.848579,A Shift,CAD Beat 03,1,666.0,950

#### Coverting Time to Decimal Minutes

In [60]:
df["Dispatch Total Response Time (min)"] = df["Dispatch Total Response Time"] / 60
df["Total On Scene Time (min)"] = df["Total On Scene Time"] / 60
df["Total Time Alarm to Last Unit Cleared (min)"] = df["Total Time Alarm to Last Unit Cleared"] / 60

# Dropping original columns
df = df.drop(columns=["Dispatch Total Response Time"])
df = df.drop(columns=["Total On Scene Time"])
df = df.drop(columns=["Total Time Alarm to Last Unit Cleared"])
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
20417,2026-04-17,07:03:43,0,2611887,"Detector activation, no fire - unintentional",700 - False Alarm,35.999245,-78.837029,C Shift,FS 8,2,7.316667,3.350000,10.033333
29217,2026-05-25,15:07:43,0,2616162,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.989960,-78.848770,B Shift,FS 3,2,6.983333,6.166667,12.283333
26133,2025-11-22,10:31:20,0,2537545,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.907547,-78.981194,C Shift,CAD Beat 16,2,4.416667,58.933333,63.266667
24160,2025-10-21,12:35:02,0,2533745,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.874172,-78.839371,C Shift,CAD Beat 19,1,7.000000,10.266667,17.083333
7742,2025-11-08,22:45:17,0,2535923,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.989338,-78.892601,A Shift,CAD Beat 01,1,6.316667,18.766667,24.600000

#### Dropping "Shift" from the Shift column

In [61]:
df["Shift"] = df["Shift"].str.strip().str.replace("Shift", "", regex=False)
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
21891,2026-04-18,13:57:39,0,2612031,CO detector activation due to malfunction,700 - False Alarm,35.975262,-78.838661,B,FS 8,1,7.600000,5.833333,12.316667
11266,2026-04-05,09:00:00,0,2610518,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.013165,-78.885658,A,FS 9,1,4.716667,15.833333,20.450000
33051,2025-07-13,14:24:50,0,2522109,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,0.000000,0.000000,A,CAD Beat 06,1,3.283333,10.666667,13.950000
32316,2025-08-08,15:15:08,0,2525158,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.993485,-78.873596,A,CAD Beat 03,1,2.766667,21.583333,23.983333
15552,2025-12-20,18:45:40,0,2540676,Alarm system sounded due to malfunction,700 - False Alarm,35.908253,-78.985481,C,CAD Beat 16,2,3.483333,22.333333,25.133333

#### Dropping "FS" and "CAD Beat" from Station Column and any zero in front of the number e.g in 05

In [62]:
df["Station"] = (
    df["Station"]
    .str.strip()
    .str.replace("FS", "", regex=False)
    .str.replace("CAD Beat", "", regex=False)
    .str.replace(r"\b0+(\d+)\b", r"\1", regex=True)
)

display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
2454,2025-10-13,15:09:05,0,2532768,Motor vehicle accident with injuries,300 - Rescue & EMS,35.979630,-78.813049,A,8,2,5.800000,39.666667,43.783333
29241,2025-09-08,13:29:30,0,2528780,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.079166,-78.891457,C,15,1,8.333333,7.450000,15.516667
28273,2026-05-22,21:53:34,0,2615910,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.959087,-78.976677,A,11,2,7.700000,10.233333,17.666667
3949,2026-02-06,04:25:17,0,2604041,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.004173,-78.956734,C,11,1,9.250000,4.616667,13.483333
16632,2025-09-08,06:44:37,0,2528738,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.938103,-78.897949,A,4,1,4.866667,12.083333,16.600000

#### Filtering out Stations that not Stations 1-19

In [63]:
# Converting Station to numeric (invalid values become NaN)
df["Station"] = pd.to_numeric(df["Station"], errors="coerce")

# Keeping only stations 1–19
df = df[df["Station"].between(1, 19)]

display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
10122,2025-11-24,09:43:14,0,2537757,Dumpster or other outside trash receptacle fire,100 - Fire,35.991940,-78.868828,C,3.0,2,3.216667,9.933333,12.150000
28430,2025-12-03,16:25:42,0,2538740,Gas leak (natural gas or LPG),400 - Hazardous Condition,36.076096,-78.894203,C,15.0,4,8.833333,14.100000,21.883333
10347,2026-03-06,08:44:57,0,2607165,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.869038,-78.858070,A,19.0,1,5.516667,8.366667,13.550000
15593,2025-08-18,08:08:58,0,2526259,Alarm system sounded due to malfunction,700 - False Alarm,35.974422,-78.897797,C,4.0,2,7.000000,8.100000,13.016667
7084,2025-10-28,15:51:06,0,2534618,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.046665,-78.889595,A,7.0,1,6.400000,4.483333,10.583333

#### Adding Battalion Column

In [64]:
# Battalion mapping
battalion_map = {
    "1": 1,
    "2": 1,
    "3": 4,
    "4": 1,
    "5": 1,
    "6": 3,
    "7": 2,
    "8": 4,
    "9": 4,
    "10": 2,
    "11": 1,
    "12": 3,
    "13": 4,
    "14": 2,
    "15": 2,
    "16": 3,
    "17": 4,
    "18": 3,
    "19": 3
}

# Adding Battalion column
df["Battalion"] = df["Station"].astype(str).map(battalion_map)

display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min),Battalion
27440,2025-10-02,03:12:52,0,2531424,No incident found on arrival at dispatch address,600 - Good Intent Call,36.043636,-78.905212,B,7.0,2,2.783333,8.050000,9.083333,NaN
7725,2025-07-15,18:26:47,0,2522357,"Medical assist, assist EMS crew",300 - Rescue & EMS,0.000000,0.000000,A,18.0,1,2.183333,10.233333,12.416667,NaN
5408,2025-08-01,11:16:28,1,2524365,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.057514,-78.929153,A,7.0,1,6.700000,3.616667,8.050000,NaN
33169,2025-10-14,06:58:10,0,2532833,"Smoke detector activation, no fire - unintenti...",700 - False Alarm,35.929741,-78.910950,A,12.0,2,5.966667,2.350000,7.116667,NaN
3160,2026-03-07,09:40:16,0,2607303,"Alarm system activation, no fire - unintentional",700 - False Alarm,35.918308,-78.845680,C,13.0,2,5.700000,11.733333,15.250000,NaN

#### Exporting File to Output Folder

In [65]:
# Ensuring output folder exists
os.makedirs("output", exist_ok=True)

# Exporting cleaned dataframe
file_path = "C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/output/Compass_Data_1_Cleaned.csv"
df.to_csv(file_path, index=False)

print("Export successful: Compass_Data_1_Cleaned.csv has been created in the output folder.")

Export successful: Compass_Data_1_Cleaned.csv has been created in the output folder.