#### Importing Libraries

In [71]:
import pandas as pd
from IPython.display import display
import numpy as np
import os

#### Loading and Viewing CSV from output folder

In [72]:
df = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/output/Compass_Data_1_Cleaned.csv")
display(df.sample(5))

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\IPython\core\interactiveshell.py:3166: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min),Battalion
32232,2025-08-01,10:41:01,0.0,2524360,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.980118,-78.811844,A,8,1.0,Engine,6.816667,6.316667,12.733333,4
5118,2025-12-12,23:53:36,0.0,2539773,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.087574,-78.898911,A,15,1.0,Engine,9.866667,23.316667,32.900000,2
23674,2025-09-07,13:28:24,0.0,2528669,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.912445,-78.936310,A,18,1.0,Engine,4.166667,16.850000,20.783333,3
841,2025-10-25,20:51:44,0.0,2534288,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.989506,-78.872444,C,3,1.0,Engine,3.050000,15.933333,18.916667,4
13589,2025-11-13,03:37:13,0.0,2536456,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.933331,-78.888779,A,4,1.0,"Medical & rescue unit, other",2.400000,10.116667,12.333333,1

In [73]:
df = df.drop(columns=["Alarm Date", "Alarm Time", "EMS Apparatus Count", "Incident Type", "Shift", 
                     "Suppression Apparatus Count", "Apparatus Type", "Total On Scene Time (min)",
                      "Total Time Alarm to Last Unit Cleared (min)"])
display(df.sample(5))

,Incident Number,Incident Type Group,Latitude,Longitude,Station,Dispatch Total Response Time (min),Battalion
15904,2530655,600 - Good Intent Call,35.933678,-78.888168,4,NaN,1
26954,2605451,700 - False Alarm,35.934368,-78.885834,4,6.266667,1
28023,2525318,300 - Rescue & EMS,35.929802,-78.781075,17,4.733333,4
12089,2528049,300 - Rescue & EMS,36.039368,-78.887383,7,5.150000,2
32241,2523097,700 - False Alarm,0.000000,0.000000,10,10.433333,2

#### Loading and Viewing CSV from input folder

In [74]:
df2 = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/input/Fire_Stations_Geocoded 1.csv")
display(df2.sample(5))

,Station,Battalion,Physical.Location,lat,long
2,Station 3,4,"822 N. Miami Boulevard Durham, NC 27703",35.990902,-78.867037
4,Station 5,1,"2212 Chapel Hill Road Durham, NC 27707",35.983517,-78.930987
16,Station 17,4,"5503 Leesville Road Durham, NC 27703",35.941071,-78.796138
9,Station 10,2,"1805 Cole Mill Road Durham, NC 27712",36.041914,-78.961552
0,Station 1,1,"139 E. Morgan Street Durham, NC 27701",35.996845,-78.897998

In [75]:
df2 = df2.rename(columns={
    "lat": "Station lat",
    "long": "Station long"
})
df2 = df2.drop(columns=["Physical.Location", "Battalion"])

display(df2.sample(5))

       Station  Station lat  Station long
5    Station 6    35.933531    -78.951136
4    Station 5    35.983517    -78.930987
11  Station 12    35.915234    -78.897464
15  Station 16    35.905729    -78.982744
8    Station 9    36.018394    -78.867551

#### df3 = df2 + df

In [76]:
df2["Station"] = df2["Station"].str.replace("Station", "", regex=False).str.strip().astype(int)
df3 = df.merge(
    df2[["Station", "Station lat", "Station long"]],
    on="Station",
    how="left"
)
display(df3.sample(5))

,Incident Number,Incident Type Group,Latitude,Longitude,Station,Dispatch Total Response Time (min),Battalion,Station lat,Station long
1403,2532686,300 - Rescue & EMS,35.960258,-78.883423,4,2.683333,1,35.955776,-78.889658
2305,2521349,300 - Rescue & EMS,0.000000,0.000000,2,9.150000,1,36.014123,-78.921872
31671,2611363,700 - False Alarm,35.869282,-78.951965,18,7.750000,3,35.898550,-78.926548
7251,2615923,300 - Rescue & EMS,36.061096,-78.871666,7,6.750000,2,36.054402,-78.904624
7061,2607100,400 - Hazardous Condition,35.945202,-78.862236,4,5.750000,1,35.955776,-78.889658

#### Average Response Time by Incident Type Group

In [77]:
df3["Dispatch Total Response Time (min)"] = pd.to_numeric(
    df3["Dispatch Total Response Time (min)"],
    errors="coerce"
)

df3["Incident Type Group Avg Response Time"] = df3.groupby(
    "Incident Type Group"
)["Dispatch Total Response Time (min)"].transform("mean")

display(df3.sample(5))

,Incident Number,Incident Type Group,Latitude,Longitude,Station,Dispatch Total Response Time (min),Battalion,Station lat,Station long,Incident Type Group Avg Response Time
2851,2612563,300 - Rescue & EMS,35.924183,-78.951324,6,3.550000,3,35.933531,-78.951136,6.154858
24734,2609919,300 - Rescue & EMS,35.963860,-78.915459,5,8.183333,1,35.983517,-78.930987,6.154858
4908,2608201,300 - Rescue & EMS,36.009640,-78.893585,1,6.516667,1,35.996845,-78.897998,6.154858
11170,2604937,300 - Rescue & EMS,36.003510,-78.867065,3,3.866667,4,35.990902,-78.867037,6.154858
11576,2532225,600 - Good Intent Call,35.984249,-78.906479,1,5.216667,1,35.996845,-78.897998,7.473910

#### Average Response Time by Station

In [78]:
df3["Dispatch Total Response Time (min)"] = pd.to_numeric(
    df3["Dispatch Total Response Time (min)"],
    errors="coerce"
)

df3["Station Avg Response Time"] = df3.groupby(
    "Station"
)["Dispatch Total Response Time (min)"].transform("mean")

display(df3.sample(5))

,Incident Number,Incident Type Group,Latitude,Longitude,Station,Dispatch Total Response Time (min),Battalion,Station lat,Station long,Incident Type Group Avg Response Time,Station Avg Response Time
16287,2541078,300 - Rescue & EMS,35.949722,-78.867386,4,5.700000,1,35.955776,-78.889658,6.154858,6.236824
20824,2538897,300 - Rescue & EMS,35.955116,-78.971420,6,11.283333,3,35.933531,-78.951136,6.154858,6.551053
1719,2532046,100 - Fire,35.988369,-78.854156,3,4.633333,4,35.990902,-78.867037,6.632377,5.358302
13184,2535538,300 - Rescue & EMS,35.907715,-78.920944,18,5.233333,3,35.898550,-78.926548,6.154858,6.564342
25976,2522399,300 - Rescue & EMS,0.000000,0.000000,4,9.150000,1,35.955776,-78.889658,6.154858,6.236824

#### Exporting File to Output Folder

# Ensuring output folder exists
os.makedirs("output", exist_ok=True)

# Exporting cleaned dataframe
file_path = "C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/output/Compass_Data_2_Cleaned.csv"
df3.to_csv(file_path, index=False)

print("Export successful: Compass_Data_2_Cleaned.csv has been created in the output folder.")