#### Importing Libraries

In [44]:
import pandas as pd
from IPython.display import display
import numpy as np
import os

#### Loading and Viewing CSV from input folder

In [45]:
df = pd.read_csv("C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/input/Compass_Data_1.csv")
display(df.sample(15))

,Alarm DateTime,Dispatch Total Response Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Total On Scene Time,Total Time Alarm to Last Unit Cleared,Apparatus Type
35886,2025-12-22 23:45:56.000,511.0,0.0,2540915,"Electrical wiring/equipment problem, other",400 - Hazardous Condition,35.889442,-79.001091,C Shift,CAD Beat 16,1.0,348.0,859.0,Engine
61556,2025-11-12 16:26:18.000,327.0,0.0,2536388,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.031067,-78.936188,A Shift,CAD Beat 10,1.0,165.0,442.0,Engine
5536,2025-11-25 07:31:11.000,283.0,0.0,2537845,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.874565,-78.836441,A Shift,CAD Beat 19,2.0,1163.0,1432.0,Engine
47826,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rescue unit
49709,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine
61485,2025-08-26 00:58:37.000,429.0,0.0,2527198,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.940113,-78.894150,A Shift,CAD Beat 04,1.0,323.0,696.0,"Medical & rescue unit, other"
43763,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Medical & rescue unit, other"
3002,2026-01-18 18:39:02.000,274.0,0.0,2602086,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.876465,-78.923500,B Shift,FS 18,1.0,483.0,752.0,Engine
32719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Quint
3255,2026-02-13 00:14:01.000,296.0,0.0,2604830,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.926617,-78.851242,A Shift,FS 13,1.0,923.0,1184.0,Engine
42236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other apparatus/resource
13727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine
43321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine
33158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine
10658,2025-11-14 05:16:48.000,389.0,0.0,2536585,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.004120,-78.870132,B Shift,CAD Beat 09,1.0,815.0,1190.0,Engine

In [46]:
print(df.columns.tolist())

['Alarm DateTime', 'Dispatch Total Response Time', 'EMS Apparatus Count', 'Incident Number', 'Incident Type', 'Incident Type Group', 'Latitude', 'Longitude', 'Shift', 'Station', 'Suppression Apparatus Count', 'Total On Scene Time', 'Total Time Alarm to Last Unit Cleared', 'Apparatus Type']

#### Splitting Alarm Date Time to Alarm Date & Alarm Time

In [47]:
# Ensuring datetime type
df["Alarm DateTime"] = pd.to_datetime(df["Alarm DateTime"])

# Splitting into separate columns
df["Alarm Date"] = df["Alarm DateTime"].dt.date.astype(str)   # YYYY-MM-DD
df["Alarm Time"] = df["Alarm DateTime"].dt.time.astype(str)   # HH:MM:SS

# Dropping original column
df = df.drop(columns=["Alarm DateTime"])

# Moving new columns to the front
cols = ["Alarm Date", "Alarm Time"] + [c for c in df.columns if c not in ["Alarm Date", "Alarm Time"]]
df = df[cols]

display(df.sample(5))

,Alarm Date,Alarm Time,Dispatch Total Response Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Total On Scene Time,Total Time Alarm to Last Unit Cleared,Apparatus Type
11233,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chief officer car
9614,2026-05-12,13:27:17,327.0,0.0,2614715,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.933289,-78.772804,B Shift,FS 17,1.0,315.0,613.0,Engine
54867,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Truck or aerial
1406,2025-12-04,01:31:16,295.0,0.0,2538779,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.941998,-78.788208,C Shift,CAD Beat 17,1.0,439.0,727.0,Engine
61513,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Truck or aerial

#### Coverting Time to Decimal Minutes

In [48]:
df["Dispatch Total Response Time (min)"] = df["Dispatch Total Response Time"] / 60
df["Total On Scene Time (min)"] = df["Total On Scene Time"] / 60
df["Total Time Alarm to Last Unit Cleared (min)"] = df["Total Time Alarm to Last Unit Cleared"] / 60

# Dropping original columns
df = df.drop(columns=["Dispatch Total Response Time"])
df = df.drop(columns=["Total On Scene Time"])
df = df.drop(columns=["Total Time Alarm to Last Unit Cleared"])
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
16252,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine,NaN,NaN,NaN
59179,2026-03-03,00:21:43,0.0,3606783,Dispatched & canceled en route,600 - Good Intent Call,35.917221,-78.987083,B Shift,FS 16,1.0,Engine,2.7,0.00,2.533333
29118,2026-05-03,08:02:04,0.0,2613650,Authorized controlled burning,600 - Good Intent Call,35.993523,-78.895889,B Shift,FS 1,1.0,Engine,6.4,0.65,3.433333
5844,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine,NaN,NaN,NaN
10413,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Truck or aerial,NaN,NaN,NaN

#### Dropping "Shift" from the Shift column

In [49]:
df["Shift"] = df["Shift"].str.strip().str.replace("Shift", "", regex=False)
display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
36801,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine,NaN,NaN,NaN
34639,2025-07-21,14:54:31,0.0,2523036,"Medical assist, assist EMS crew",300 - Rescue & EMS,0.000000,0.000000,C,CAD Beat 04,1.0,"Medical & rescue unit, other",5.333333,4.516667,9.850000
20854,2026-02-07,21:47:02,0.0,2604260,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.085964,-78.941055,C,FS 14,1.0,Engine,3.250000,31.750000,34.916667
19869,2026-02-24,16:21:46,0.0,2606174,"Steam, other gas mistaken for smoke, other",600 - Good Intent Call,36.046665,-78.901924,B,FS 7,1.0,Engine,3.116667,8.466667,10.250000
43051,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Engine,NaN,NaN,NaN

#### Dropping "FS" and "CAD Beat" from Station Column and any zero in front of the number e.g in 05

In [50]:
df["Station"] = (
    df["Station"]
    .astype(str)
    .str.strip()
    .str.replace("FS", "", regex=False)
    .str.replace("CAD Beat", "", regex=False)
    .str.replace(r"[^\d]", "", regex=True)   # keeping only digits
)

# Converting to numeric and force integer
df["Station"] = pd.to_numeric(df["Station"], errors="coerce")
df = df.dropna(subset=["Station"])
df["Station"] = df["Station"].astype(int)

display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
17246,2025-08-26,02:26:58,0.0,2527203,"Smoke scare, odor of smoke",600 - Good Intent Call,35.997597,-78.902527,A,1,11.0,Chief officer car,2.700000,49.900000,50.833333
23938,2026-04-22,19:25:00,0.0,2612554,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.992035,-78.925659,A,5,1.0,Engine,6.700000,11.200000,17.716667
22463,2026-04-21,23:59:34,0.0,2612456,Power line down,400 - Hazardous Condition,35.965305,-78.910294,C,4,5.0,Truck or aerial,7.083333,68.300000,73.016667
43027,2026-03-25,21:30:49,0.0,2609387,"Detector activation, no fire - unintentional",700 - False Alarm,35.994003,-78.802986,A,8,1.0,Quint,7.366667,2.266667,8.650000
58759,2025-09-05,15:53:01,0.0,2528434,Assist police or other governmental agency,500 - Service Call,35.979473,-78.845345,B,8,1.0,Engine,6.583333,20.916667,26.866667

#### Filtering out Stations that not Stations 1-19

In [51]:
# Converting Station to numeric (invalid values become NaN)
df["Station"] = pd.to_numeric(df["Station"], errors="coerce")

# Keeping only stations 1–19
df = df[df["Station"].between(1, 19)]

display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min)
20753,2025-11-29,12:40:51,0.0,2538288,No incident found on arrival at dispatch address,600 - Good Intent Call,36.040474,-78.886208,A,9,2.0,Engine,6.700000,4.116667,8.033333
47529,2025-09-04,15:32:05,0.0,2528306,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.975815,-78.787399,C,8,2.0,Engine,4.266667,13.000000,16.666667
30426,2025-11-27,09:54:10,0.0,2538076,Alarm system sounded due to malfunction,700 - False Alarm,36.006828,-78.947723,A,2,2.0,Engine,8.716667,19.650000,27.433333
33220,2025-07-29,05:35:14,0.0,2523942,Motor vehicle accident with injuries,300 - Rescue & EMS,0.000000,0.000000,A,4,2.0,"Medical & rescue unit, other",4.833333,18.766667,23.600000
44156,2026-04-09,16:40:04,0.0,2611025,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.987568,-78.887474,A,3,1.0,Engine,4.766667,8.200000,12.600000

#### Adding Battalion Column

In [52]:
# Battalion mapping
battalion_map = {
    "1": 1,
    "2": 1,
    "3": 4,
    "4": 1,
    "5": 1,
    "6": 3,
    "7": 2,
    "8": 4,
    "9": 4,
    "10": 2,
    "11": 1,
    "12": 3,
    "13": 4,
    "14": 2,
    "15": 2,
    "16": 3,
    "17": 4,
    "18": 3,
    "19": 3
}

# Adding Battalion column
df["Battalion"] = df["Station"].astype(str).map(battalion_map)

display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min),Battalion
22585,2025-07-08,07:20:50,0.0,2521479,No incident found on arrival at dispatch address,600 - Good Intent Call,0.000000,0.000000,C,14,2.0,Quint,5.116667,0.250000,5.366667,2
1046,2025-07-10,07:43:45,0.0,2521731,"Smoke detector activation, no fire - unintenti...",700 - False Alarm,0.000000,0.000000,C,16,2.0,Engine,3.783333,24.050000,27.833333,3
10265,2025-07-25,09:15:10,0.0,2523462,"Medical assist, assist EMS crew",300 - Rescue & EMS,0.000000,0.000000,C,2,1.0,Engine,7.833333,2.916667,10.750000,1
1504,2025-08-17,09:50:04,0.0,2526138,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.877548,-78.929947,B,18,1.0,Engine,9.750000,2.416667,12.083333,3
32337,2026-03-19,16:11:51,0.0,2608671,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,36.005322,-78.921410,B,2,2.0,Truck or aerial,3.400000,6.166667,9.383333,1

#### Dropping Longitude or Latitude that are blank or 0

In [53]:
# Ensuring numeric
df["Longitude"] = pd.to_numeric(df["Longitude"], errors="coerce")
df["Latitude"] = pd.to_numeric(df["Latitude"], errors="coerce")

# Droping blanks (NaN) or zeros
df = df[
    df["Longitude"].notna() &
    df["Latitude"].notna() &
    (df["Longitude"] != 0) &
    (df["Latitude"] != 0)
]

display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min),Battalion
15828,2025-09-29,14:17:58,0.0,2531131,"Medical assist, assist EMS crew",300 - Rescue & EMS,35.943768,-78.966270,B,6,1.0,Truck or aerial,5.466667,6.616667,11.800000,3
27165,2025-10-14,08:39:08,0.0,2532841,Rescue or EMS standby,300 - Rescue & EMS,35.982201,-78.902802,B,1,1.0,Engine,9.683333,13.000000,21.950000,1
34550,2026-04-30,21:41:46,0.0,2613399,"Smoke detector activation, no fire - unintenti...",700 - False Alarm,35.900902,-78.987068,C,16,2.0,Engine,4.383333,6.050000,9.133333,3
52366,2026-03-15,12:16:36,0.0,2608229,"Unintentional transmission of alarm, other",700 - False Alarm,35.882946,-78.865356,B,19,1.0,Engine,6.083333,5.866667,10.550000,3
12981,2025-09-30,15:36:41,0.0,2531258,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.001339,-78.910728,A,1,1.0,"Medical & rescue unit, other",3.800000,6.233333,9.850000,1

#### Dropping blank rows of Apparatus Type

In [54]:
# Dropping rows where Apparatus Type is blank or null
df = df[
    df["Apparatus Type"].notna() &
    (df["Apparatus Type"].astype(str).str.strip() != "")
]

display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min),Battalion
10074,2026-05-05,08:12:37,0.0,2613886,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.979485,-78.870232,A,3,1.0,Engine,4.083333,5.200000,9.083333,4
36779,2026-04-21,09:07:11,0.0,2612368,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.972012,-78.900055,C,4,1.0,Truck or aerial,4.583333,15.750000,19.900000,1
18144,2025-12-17,22:50:00,0.0,2540343,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.941521,-78.894829,B,4,1.0,Engine,8.250000,16.700000,24.883333,1
37890,2025-10-11,18:38:37,0.0,2532559,Gas leak (natural gas or LPG),400 - Hazardous Condition,35.995327,-78.901527,A,1,11.0,Truck or aerial,2.716667,29.216667,30.383333,1
44305,2025-08-14,19:04:26,0.0,2525852,Rescue or EMS standby,300 - Rescue & EMS,35.888039,-78.848473,A,19,1.0,Quint,4.950000,23.250000,27.716667,3

#### Dropping where Dispatch Total Response Time (min) is NaN or 0

In [55]:
# Ensuring numeric
df["Dispatch Total Response Time (min)"] = pd.to_numeric(
    df["Dispatch Total Response Time (min)"],
    errors="coerce"
)

# Dropping NaN or 0 values
df = df[
    df["Dispatch Total Response Time (min)"].notna() &
    (df["Dispatch Total Response Time (min)"] != 0)
]

display(df.sample(5))

,Alarm Date,Alarm Time,EMS Apparatus Count,Incident Number,Incident Type,Incident Type Group,Latitude,Longitude,Shift,Station,Suppression Apparatus Count,Apparatus Type,Dispatch Total Response Time (min),Total On Scene Time (min),Total Time Alarm to Last Unit Cleared (min),Battalion
42254,2025-09-01,16:08:41,0.0,2527950,"Medical assist, assist EMS crew",300 - Rescue & EMS,36.028759,-78.925514,B,2,2.0,Quint,3.583333,4.483333,7.966667,1
30060,2025-09-20,11:53:56,0.0,2530116,Alarm system sounded due to malfunction,700 - False Alarm,36.010246,-78.935554,B,2,2.0,Truck or aerial,5.416667,12.116667,16.166667,1
16760,2025-11-09,04:56:32,0.0,2535951,No incident found on arrival at dispatch address,600 - Good Intent Call,36.088100,-78.878197,A,2,1.0,Engine,10.966667,0.083333,9.533333,1
26363,2025-10-13,20:57:50,0.0,2532791,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.956665,-78.893951,A,4,1.0,"Medical & rescue unit, other",3.900000,8.716667,12.533333,1
45767,2026-04-06,10:09:42,0.0,2610645,"EMS call, excluding vehicle accident with injury",300 - Rescue & EMS,35.901020,-78.894165,C,12,1.0,"Medical & rescue unit, other",4.750000,25.216667,29.116667,3

#### Exporting File to Output Folder

In [56]:
# Ensuring output folder exists
os.makedirs("output", exist_ok=True)

# Exporting cleaned dataframe
file_path = "C:/Users/AmarachiOny/Desktop/DFD_Projects/Python/Compass_ESO_Data/output/Compass_Data_1_Cleaned.csv"
df.to_csv(file_path, index=False)

print("Export successful: Compass_Data_1_Cleaned.csv has been created in the output folder.")

Export successful: Compass_Data_1_Cleaned.csv has been created in the output folder.